--[[

    Please do NOT edit this file but go to http://wow.curseforge.com/addons/armory/localization/ instead.
    
    The contents of this file will be generated automatically.
    
]]--

local L = LibStub("AceLocale-3.0"):NewLocale("Armory", "enUS", true);

--@localization(locale="enUS", format="lua_additive_table", handle-subnamespaces="none")@
