--[[

    Please do NOT edit this file but go to http://wow.curseforge.com/addons/armory/localization/ instead.
    
    The contents of this file will be generated automatically.
    
]]--

local L = LibStub("AceLocale-3.0"):NewLocale("Armory", "esES");
if ( not L ) then 
    return;
end

--@localization(locale="esES", format="lua_additive_table", handle-unlocalized="english", handle-subnamespaces="none")@
