--[[

    Please do NOT edit this file but go to http://wow.curseforge.com/addons/armory/localization/ instead.
    
    The contents of this file will be generated automatically.

]]--

local L = LibStub("AceLocale-3.0"):NewLocale("Armory", "esMX");
if ( not L ) then 
    return;
end

-- Armory
L["ARMORY_ALTS"] = "Alts"
L["ARMORY_BAGS"] = "Bolsas"
L["ARMORY_BANK_CONTAINER_NAME"] = "Banco"
--[[Translation missing --]]
L["ARMORY_BONUS_PATTERN"] = "(.+) Bonus"
--[[Translation missing --]]
L["ARMORY_BUZZ_WORDS"] = [=[of
the]=]
--[[Translation missing --]]
L["ARMORY_BY_DATE"] = "View by date"
--[[Translation missing --]]
L["ARMORY_BY_GROUP"] = "View by group"
--[[Translation missing --]]
L["ARMORY_CAN_LEARN"] = "Learnable by"
--[[Translation missing --]]
L["ARMORY_CHECK_CD_NONE"] = "No cooldowns found"
L["ARMORY_CHECK_MAIL_DISABLED"] = "Revisión de expiración del correo esta deshabilitado."
L["ARMORY_CHECK_MAIL_MESSAGE"] = "La bandeja de entrada de %1$s (%2$s) contiene un correo '%3$s' que expirara en %4$s!"
L["ARMORY_CHECK_MAIL_NONE"] = "No se encontraron correos en el buzón que estén apunto de expirar."
L["ARMORY_CHECK_MAIL_POPUP"] = "Hay muchos correos que están apunto de expirar. Usa '/ar check' para mas detalles."
L["ARMORY_CMD_CHECK"] = "Checar"
--[[Translation missing --]]
L["ARMORY_CMD_CHECK_INVALID"] = "Specify the number of days to check or none for default."
L["ARMORY_CMD_CHECK_MENUTEXT"] = "Revisión expiración de correo."
L["ARMORY_CMD_CHECK_TEXT"] = "Revisar inventario de correos en bandeja de entrada  para ver su expiración."
--[[Translation missing --]]
L["ARMORY_CMD_CHECKCD"] = "cooldown|cd"
--[[Translation missing --]]
L["ARMORY_CMD_CHECKCD_TEXT"] = "check tradeskill cooldowns"
L["ARMORY_CMD_CONFIG"] = "Configuracion"
L["ARMORY_CMD_CONFIG_TEXT"] = "Abrir panel de configuración"
L["ARMORY_CMD_DELETE"] = "Borrar"
L["ARMORY_CMD_DELETE_ALL"] = "Todos"
L["ARMORY_CMD_DELETE_ALL_MSG"] = "Bases de datos de Armory han sido limpiadas."
L["ARMORY_CMD_DELETE_ALL_TEXT"] = "Borrar toda la base de datos"
L["ARMORY_CMD_DELETE_CHAR"] = "Personaje"
L["ARMORY_CMD_DELETE_CHAR_MSG"] = "Entrada de Armory para '%1$s' en el reino '%2$s' ha sido removida."
L["ARMORY_CMD_DELETE_CHAR_NOT_FOUND"] = "Entrada de Armory para '%1$s' en el reino '%2$s' no fue encontrada!"
L["ARMORY_CMD_DELETE_CHAR_PARAMS_TEXT"] = "[nombre] [reino]"
L["ARMORY_CMD_DELETE_CHAR_TEXT"] = "Borrar personaje"
L["ARMORY_CMD_DELETE_REALM"] = "Reino"
L["ARMORY_CMD_DELETE_REALM_MSG"] = "Reino en Armory '%s' fue limpiado."
L["ARMORY_CMD_DELETE_REALM_NOT_FOUND"] = "Reino en Armory '%s' no fue encontrado!"
L["ARMORY_CMD_DELETE_REALM_PARAMS_TEXT"] = "[nombre]"
L["ARMORY_CMD_DELETE_REALM_TEXT"] = "Borrar todos los datos del reino"
L["ARMORY_CMD_DOWNLOAD"] = "Descargar"
L["ARMORY_CMD_DOWNLOAD_TEXT"] = "Descargar recetas de miembros de la hermandad"
L["ARMORY_CMD_FIND"] = "Buscar"
L["ARMORY_CMD_FIND_ALL"] = "Todos"
L["ARMORY_CMD_FIND_FOUND"] = "Numero total de Occurrencias: %d"
--[[Translation missing --]]
L["ARMORY_CMD_FIND_GLYPH"] = "glyph"
--[[Translation missing --]]
L["ARMORY_CMD_FIND_GLYPH_TOOLTIP"] = "Use '?' or '%s' to find glyphs you haven't learned yet."
L["ARMORY_CMD_FIND_INVENTORY"] = "Inventario"
L["ARMORY_CMD_FIND_ITEM"] = "Objeto"
L["ARMORY_CMD_FIND_MENUTEXT"] = "Buscar en la Base de Datos"
L["ARMORY_CMD_FIND_NOT_FOUND"] = "No encontrado"
L["ARMORY_CMD_FIND_PARAMS_TEXT"] = " [nombreparte] "
L["ARMORY_CMD_FIND_QUEST"] = "Misión"
L["ARMORY_CMD_FIND_QUEST_REWARD"] = "Recompensa de Misión"
L["ARMORY_CMD_FIND_SKILL"] = "Habilidad"
L["ARMORY_CMD_FIND_SPELL"] = "Hechizo"
L["ARMORY_CMD_FIND_TEXT"] = "buscar información en la base de datos local"
L["ARMORY_CMD_HELP"] = "Ayuda"
L["ARMORY_CMD_HELP_TEXT"] = "muestra esta lista de usos"
L["ARMORY_CMD_LOOKUP"] = "Busqueda"
L["ARMORY_CMD_LOOKUP_MENUTEXT"] = "Retroalimentar informacion"
L["ARMORY_CMD_LOOKUP_TEXT"] = "Retroalimentar información de otros jugadores"
L["ARMORY_CMD_RESET"] = "Reestablecer"
L["ARMORY_CMD_RESET_FRAME"] = "Marcos"
L["ARMORY_CMD_RESET_FRAME_MENUTEXT"] = "Resetear posiciones en pantalla"
L["ARMORY_CMD_RESET_FRAME_SUCCESS"] = "Resetear frames"
L["ARMORY_CMD_RESET_FRAME_TEXT"] = "Colocar posiciones de pantalla a pociones de pantalla originales"
L["ARMORY_CMD_RESET_SETTINGS"] = "Configuraciones"
L["ARMORY_CMD_RESET_SETTINGS_SUCCESS"] = "Opciones restablecidas"
L["ARMORY_CMD_RESET_SETTINGS_TEXT"] = "Colocar todas las opciones a opciones por defaults"
--[[Translation missing --]]
L["ARMORY_CMD_SET_ALTCLICKSEARCH_MENUTEXT"] = "Search Alt-clicked link"
--[[Translation missing --]]
L["ARMORY_CMD_SET_ALTCLICKSEARCH_TEXT"] = "start a search when Alt-clicking a chat link"
--[[Translation missing --]]
L["ARMORY_CMD_SET_ALTCLICKSEARCH_TOOLTIP"] = "If enabled, the find command will be invoked while holding down the Alt key and clicking a searchable link in the chat frame."
--[[Translation missing --]]
L["ARMORY_CMD_SET_CHECKBUTTON_MENUTEXT"] = "Hide Armory button"
--[[Translation missing --]]
L["ARMORY_CMD_SET_CHECKBUTTON_TEXT"] = "hide the Armory check button on the character frame"
--[[Translation missing --]]
L["ARMORY_CMD_SET_CHECKBUTTON_TOOLTIP"] = "If enabled, the Armory check button in the lower left corner of the character frame will not be shown."
--[[Translation missing --]]
L["ARMORY_CMD_SET_CHECKCOOLDOWNS_MENUTEXT"] = "Check available cooldowns"
--[[Translation missing --]]
L["ARMORY_CMD_SET_CHECKCOOLDOWNS_TEXT"] = "check available cooldowns on startup"
--[[Translation missing --]]
L["ARMORY_CMD_SET_CHECKCOOLDOWNS_TOOLTIP"] = "If enabled, tradeskill cooldowns that became available while you were offline will be displayed when you log in."
--[[Translation missing --]]
L["ARMORY_CMD_SET_COLLAPSE_MENUTEXT"] = "Collapse character frame"
--[[Translation missing --]]
L["ARMORY_CMD_SET_COLLAPSE_TEXT"] = "collapse the character frame"
--[[Translation missing --]]
L["ARMORY_CMD_SET_COLLAPSE_TOOLTIP"] = "If enabled, the character frame will be collapsed when Armory's layout is active."
--[[Translation missing --]]
L["ARMORY_CMD_SET_COOLDOWNEVENTS_MENUTEXT"] = "Include tradeskill cooldowns"
--[[Translation missing --]]
L["ARMORY_CMD_SET_COOLDOWNEVENTS_TEXT"] = "include tradeskill cooldowns in event list"
--[[Translation missing --]]
L["ARMORY_CMD_SET_COOLDOWNEVENTS_TOOLTIP"] = "If enabled, tradeskill cooldowns will be included in Armory's event list."
L["ARMORY_CMD_SET_COUNTALL_MENUTEXT"] = "Incluir todos los reinos en cuenta"
L["ARMORY_CMD_SET_COUNTALL_TEXT"] = "Incluir cuantos Objetos por todos los Reinos"
L["ARMORY_CMD_SET_COUNTALL_TOOLTIP"] = "Si se habilita, los totales se muestran para todos los reinos, de otra manera solo para el reino actual e interconectados con el."
--[[Translation missing --]]
L["ARMORY_CMD_SET_COUNTPERSLOT_MENUTEXT"] = "Totals per bag/bank slot"
--[[Translation missing --]]
L["ARMORY_CMD_SET_COUNTPERSLOT_TEXT"] = "show item counts per bag/bank slot"
--[[Translation missing --]]
L["ARMORY_CMD_SET_COUNTPERSLOT_TOOLTIP"] = "If enabled, items counts are shown per bag or bank slot, where slot '0' represents the backpack or bank itself."
--[[Translation missing --]]
L["ARMORY_CMD_SET_COUNTXFACTION_MENUTEXT"] = "Include all factions in counts"
--[[Translation missing --]]
L["ARMORY_CMD_SET_COUNTXFACTION_TEXT"] = "include item counts for all factions"
--[[Translation missing --]]
L["ARMORY_CMD_SET_COUNTXFACTION_TOOLTIP"] = "If enabled, totals are shown for all factions; otherwise only for the current faction."
L["ARMORY_CMD_SET_DEFAULTSEARCH_MENUTEXT"] = "Dominio Default de búsqueda"
L["ARMORY_CMD_SET_DEFAULTSEARCH_TEXT"] = "Dominio Default"
L["ARMORY_CMD_SET_DEFAULTSEARCH_TOOLTIP"] = "El dominio de búsqueda a usar cuando ninguno es especificado."
--[[Translation missing --]]
L["ARMORY_CMD_SET_ENABLED_MENUTEXT"] = "Enable character"
--[[Translation missing --]]
L["ARMORY_CMD_SET_ENABLED_TEXT"] = "include this character in Armory"
--[[Translation missing --]]
L["ARMORY_CMD_SET_ENABLED_TOOLTIP"] = [=[If enabled, Armory will perform data collection for the current character.
Note that changing this option will result in a UI reload.]=]
--[[Translation missing --]]
L["ARMORY_CMD_SET_EVENTLOCALTIME_MENUTEXT"] = "Use local time for events"
--[[Translation missing --]]
L["ARMORY_CMD_SET_EVENTLOCALTIME_TEXT"] = "use local time in event list"
--[[Translation missing --]]
L["ARMORY_CMD_SET_EVENTLOCALTIME_TOOLTIP"] = "If enabled, local time is used in the event list; otherwise the realm time."
--[[Translation missing --]]
L["ARMORY_CMD_SET_EVENTWARNINGS_MENUTEXT"] = "Event notifications"
--[[Translation missing --]]
L["ARMORY_CMD_SET_EVENTWARNINGS_TEXT"] = "enable event notifications"
--[[Translation missing --]]
L["ARMORY_CMD_SET_EVENTWARNINGS_TOOLTIP"] = "If enabled, you will be warned about confirmed events of your characters that are about to become due."
L["ARMORY_CMD_SET_EXPDAYS_INVALID"] = " %1$s debe ser entre 0 (sin advertencia) y %2$d días! "
L["ARMORY_CMD_SET_EXPDAYS_PARAMS_TEXT"] = "numdías "
L["ARMORY_CMD_SET_EXPDAYS_TEXT"] = "Nivel de advertencia para expiración de correos en la bandeja de entrada"
L["ARMORY_CMD_SET_EXPDAYS_TOOLTIP"] = "El buzón  será revisado por correos que vayan a expirar con el numero especificado de días (0 deshabilita la advertencia)."
L["ARMORY_CMD_SET_EXTENDEDSEARCH_MENUTEXT"] = "Búsqueda extendida"
L["ARMORY_CMD_SET_EXTENDEDSEARCH_TEXT"] = "mirar en el texto de la tooltip por coincidencias cuando uso buscar"
L["ARMORY_CMD_SET_EXTENDEDSEARCH_TOOLTIP"] = "Si se Habilita, el comando buscar mirara en el texto de la tooltip por coincidencias; de otra manera solo el nombre es revisado."
L["ARMORY_CMD_SET_EXTENDEDTRADE_MENUTEXT"] = "Habilita filtros de profesión"
L["ARMORY_CMD_SET_EXTENDEDTRADE_TEXT"] = "Habilita filtros de  subclase y ranura "
L["ARMORY_CMD_SET_EXTENDEDTRADE_TOOLTIP"] = [=[Si se habilita, las profesiones pueden ser filtradas en subclases y/o ranuras de objeto.
Si tu experimentas problemas con otros add-ons puedes deshabilitar esta característica para obtener una lista simple que no dispara cualquier evento (una lista categorizada es elegible si usas shift+click en el botón link)]=]
L["ARMORY_CMD_SET_GLOBALSEARCH_MENUTEXT"] = "Búsqueda Global"
L["ARMORY_CMD_SET_GLOBALSEARCH_TEXT"] = "Buscar en todos los reinos usando el comando buscar"
L["ARMORY_CMD_SET_GLOBALSEARCH_TOOLTIP"] = "Si se habilita, el comando buscar ira a través de toda la base de datos; de otra manera solo en el reino actual e interconectados será la búsqueda."
--[[Translation missing --]]
L["ARMORY_CMD_SET_HIDELOGON_MENUTEXT"] = "Hide warning when logging in"
--[[Translation missing --]]
L["ARMORY_CMD_SET_HIDELOGON_TEXT"] = "don't show a warning when logging in"
--[[Translation missing --]]
L["ARMORY_CMD_SET_HIDELOGON_TOOLTIP"] = "If enabled, the warning will not be displayed when you log in."
L["ARMORY_CMD_SET_HIDEMMTOOLBAR_MENUTEXT"] = "Ocultar el botón en el minimapa con barras de herramientas"
L["ARMORY_CMD_SET_HIDEMMTOOLBAR_TEXT"] = "Ocultar el botón en el minimapa cuando Titan/Fubar están cargados "
L["ARMORY_CMD_SET_HIDEMMTOOLBAR_TOOLTIP"] = "Si se habilita, el botón del minimapa se ocultara automáticamente cuando Titan o FuBar esta cargado."
L["ARMORY_CMD_SET_IGNOREALTS_MENUTEXT"] = "Ignorar correos de alts"
L["ARMORY_CMD_SET_IGNOREALTS_TEXT"] = "Ignorar advertencias de correos de alts"
L["ARMORY_CMD_SET_IGNOREALTS_TOOLTIP"] = "Si esta habilitado, El mensaje de advertencia no será mostrado para correos que fueron enviados (no regresados) por uno de tus personajes. Nota que los personajes deben estar en Armory para que esto funcione."
L["ARMORY_CMD_SET_LASTVIEWED_MENUTEXT"] = "Recordar selección "
L["ARMORY_CMD_SET_LASTVIEWED_TEXT"] = "Recordar el ultimo personaje visto"
L["ARMORY_CMD_SET_LASTVIEWED_TOOLTIP"] = "Si se habilita, el ultimo personaje seleccionado será almacenado entre sesiones."
L["ARMORY_CMD_SET_LDBLABEL_MENUTEXT"] = "Habilitar Etiqueta LDB"
L["ARMORY_CMD_SET_LDBLABEL_TEXT"] = "Habilitar mostrar etiqueta de LibDataBroker"
L["ARMORY_CMD_SET_LDBLABEL_TOOLTIP"] = "Si se habilita, una etiqueta de texto es mostrada en la pantalla add-ons de LibDataBroker add-ons"
--[[Translation missing --]]
L["ARMORY_CMD_SET_MAILCHECKCOUNT_MENUTEXT"] = "Check for remaining mail"
--[[Translation missing --]]
L["ARMORY_CMD_SET_MAILCHECKCOUNT_TEXT"] = "check for remaining mail in the inbox"
--[[Translation missing --]]
L["ARMORY_CMD_SET_MAILCHECKCOUNT_TOOLTIP"] = "If enabled, a warning will be shown when not all mails were scanned because the inbox display limit has been exceeded."
--[[Translation missing --]]
L["ARMORY_CMD_SET_MAILCHECKVISIT_MENUTEXT"] = "Warn for unnoticed mail"
--[[Translation missing --]]
L["ARMORY_CMD_SET_MAILCHECKVISIT_TEXT"] = "include the last mailbox visit when checking for mail"
--[[Translation missing --]]
L["ARMORY_CMD_SET_MAILCHECKVISIT_TOOLTIP"] = "If enabled, a warning will be shown when a character's mailbox hasn't been opened for at least 30 minus expiration threshold number of days and therefore may contain mail without being noticed."
--[[Translation missing --]]
L["ARMORY_CMD_SET_MAILEXCLUDEVISIT_MENUTEXT"] = "Exclude this character's mailbox visit"
--[[Translation missing --]]
L["ARMORY_CMD_SET_MAILEXCLUDEVISIT_TEXT"] = "don't check this character's mailbox visit"
--[[Translation missing --]]
L["ARMORY_CMD_SET_MAILEXCLUDEVISIT_TOOLTIP"] = "If enabled, the current character's mailbox visit will be excluded from the check."
--[[Translation missing --]]
L["ARMORY_CMD_SET_MAILHIDECOUNT_MENUTEXT"] = "Hide remaining mail scan warning"
--[[Translation missing --]]
L["ARMORY_CMD_SET_MAILHIDECOUNT_TEXT"] = "don't show a warning when the mailbox is closed"
--[[Translation missing --]]
L["ARMORY_CMD_SET_MAILHIDECOUNT_TOOLTIP"] = "If enabled, the warning for remaining mail will not be shown when you close the mailbox."
L["ARMORY_CMD_SET_MMB_ANGLE_TEXT"] = "Angulo del botón en el minimapa"
--[[Translation missing --]]
L["ARMORY_CMD_SET_MMB_GLOBAL_MENUTEXT"] = "position the button the same for all characters"
--[[Translation missing --]]
L["ARMORY_CMD_SET_MMB_GLOBAL_TEXT"] = "Use same position for all"
--[[Translation missing --]]
L["ARMORY_CMD_SET_MMB_GLOBAL_TOOLTIP"] = "If enabled, the angle and radius will be the same for all characters."
L["ARMORY_CMD_SET_MMB_RADIUS_TEXT"] = "Radio del botón en el minimapa"
L["ARMORY_CMD_SET_NOVALUE"] = "Opción actual: %s"
L["ARMORY_CMD_SET_NOVALUE_TEXT"] = "Mostrar opciones actuales"
L["ARMORY_CMD_SET_OFF"] = "Deshabilitar"
L["ARMORY_CMD_SET_ON"] = "habilitar"
--[[Translation missing --]]
L["ARMORY_CMD_SET_PAUSEINCOMBAT_MENUTEXT"] = "Pause in combat"
--[[Translation missing --]]
L["ARMORY_CMD_SET_PAUSEINCOMBAT_TEXT"] = "do not scan when in combat"
--[[Translation missing --]]
L["ARMORY_CMD_SET_PAUSEINCOMBAT_TOOLTIP"] = "If enabled Armory pauses scanning when you get into combat and resumes afterwards."
--[[Translation missing --]]
L["ARMORY_CMD_SET_PAUSEININSTANCE_MENUTEXT"] = "Remain paused in instance"
--[[Translation missing --]]
L["ARMORY_CMD_SET_PAUSEININSTANCE_TEXT"] = "do not resume when in an instance"
--[[Translation missing --]]
L["ARMORY_CMD_SET_PAUSEININSTANCE_TOOLTIP"] = "If enabled, getting out of combat in an instance will not process any postponed updates. Be aware that in this case item counts in tooltips will not be updated either."
L["ARMORY_CMD_SET_PERCHARACTER_MENUTEXT"] = "Recordar por personaje"
L["ARMORY_CMD_SET_PERCHARACTER_TEXT"] = "Recordar opciones individuales"
L["ARMORY_CMD_SET_PERCHARACTER_TOOLTIP"] = "Si se habilita, los valores 'todos los personajes' y 'ultimo personaje' serán almacenados en una base por personaje."
--[[Translation missing --]]
L["ARMORY_CMD_SET_RESTRICTIVESEARCH_MENUTEXT"] = "Restrictive find"
--[[Translation missing --]]
L["ARMORY_CMD_SET_RESTRICTIVESEARCH_TEXT"] = "don't include obtainable objects when using find"
--[[Translation missing --]]
L["ARMORY_CMD_SET_RESTRICTIVESEARCH_TOOLTIP"] = "If enabled, the find command will not consider obtainable objects, like rewards or craftables, as possible matches."
--[[Translation missing --]]
L["ARMORY_CMD_SET_SCALEONMOUSEWHEEL_MENUTEXT"] = "enable mouse wheel"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SCALEONMOUSEWHEEL_TEXT"] = "Enable mouse wheel"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SCALEONMOUSEWHEEL_TOOLTIP"] = "If enabled, scrolling the mouse wheel while hovering over the background of Armory's main frame will change the UI scale."
--[[Translation missing --]]
L["ARMORY_CMD_SET_SCANONENTER_MENUTEXT"] = "Force scan on login"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SCANONENTER_TEXT"] = "force a scan on the next login"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SCANONENTER_TOOLTIP"] = [=[If enabled Armory will forcibly update all accessible character data on the next login.
This setting will reset itself automatically.]=]
L["ARMORY_CMD_SET_SEARCHALL_MENUTEXT"] = "Recordar 'todos los personajes' "
L["ARMORY_CMD_SET_SEARCHALL_TEXT"] = "Recordar opción 'todos los personajes' en el inventario"
L["ARMORY_CMD_SET_SEARCHALL_TOOLTIP"] = "Si se habilita, la opción  'todos los personajes' en la vista de la lista del inventario será almacenada entre sesiones."
L["ARMORY_CMD_SET_SHAREALL_MENUTEXT"] = "Compartir todos los personajes"
L["ARMORY_CMD_SET_SHAREALL_TEXT"] = "compartir información de todos tus personajes"
L["ARMORY_CMD_SET_SHAREALL_TOOLTIP"] = "Si se habilita, la información de todos tus personajes será compartida, de otra manera solo la información de tu personaje actual."
L["ARMORY_CMD_SET_SHAREALT_MENUTEXT"] = "Revelar relaciones"
L["ARMORY_CMD_SET_SHAREALT_TEXT"] = "Revelar relaciones con otros personajes"
L["ARMORY_CMD_SET_SHAREALT_TOOLTIP"] = "Si se habilita, las relaciones entre el personaje actual y tus otros personajes será visible (ejem. mostrar como alt). Deshabilitar hace mostrar solo al personaje."
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHARECHANNEL_MENUTEXT"] = "enable lookup channel"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHARECHANNEL_TEXT"] = "Enable custom channel"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHARECHANNEL_TOOLTIP"] = "If enabled, lookup requests can be sent through the provided channel which you can share with a specific group of players."
L["ARMORY_CMD_SET_SHARECHARACTER_MENUTEXT"] = "compartir la información del personaje"
L["ARMORY_CMD_SET_SHARECHARACTER_TEXT"] = "compartir la información de tu personaje"
L["ARMORY_CMD_SET_SHARECHARACTER_TOOLTIP"] = "Si se habilita, otros usuarios de Armory pueden inspeccionar tu equipo y talentos"
L["ARMORY_CMD_SET_SHAREGUILD_MENUTEXT"] = "Compartir personajes de hermandad"
L["ARMORY_CMD_SET_SHAREGUILD_TEXT"] = "Compartir información de personajes de hermandad"
L["ARMORY_CMD_SET_SHAREGUILD_TOOLTIP"] = "Si se habilita, la información de personajes con la misma hermandad es compartida,"
L["ARMORY_CMD_SET_SHAREINCOMBAT_MENUTEXT"] = "Compartir en combate"
L["ARMORY_CMD_SET_SHAREINCOMBAT_TEXT"] = "Compartir mientras se esta en combate"
L["ARMORY_CMD_SET_SHAREINCOMBAT_TOOLTIP"] = "Si se habilita, tu responderás consultas mientras estas en combate. Deshabilitar puede mejorar el rendimiento "
L["ARMORY_CMD_SET_SHAREININSTANCE_MENUTEXT"] = "Compartir en instancia"
L["ARMORY_CMD_SET_SHAREININSTANCE_TEXT"] = "Compartir mientras estas en una instancia"
L["ARMORY_CMD_SET_SHAREININSTANCE_TOOLTIP"] = "Si se habilita, tu responderás consultas mientras estas en una instancia. Deshabilitar puede mejorar el rendimiento "
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHAREITEMS_MENUTEXT"] = "Share items"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHAREITEMS_TEXT"] = "share your inventory items"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHAREITEMS_TOOLTIP"] = "If enabled, other Armory users who are using the same custom channel can search for items in your inventory."
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHAREQUESTS_MENUTEXT"] = "Share quests"
L["ARMORY_CMD_SET_SHAREQUESTS_TEXT"] = "Compartir tus misiones"
L["ARMORY_CMD_SET_SHAREQUESTS_TOOLTIP"] = "Si se habilita, otros usuarios de Armory pueden buscar tus misiones."
L["ARMORY_CMD_SET_SHARESKILLS_MENUTEXT"] = "Compartir profesiones"
L["ARMORY_CMD_SET_SHARESKILLS_TEXT"] = "Comparte tus recetas de profesión"
L["ARMORY_CMD_SET_SHARESKILLS_TOOLTIP"] = "si se habilita, otros usuarios de Armory pueden buscar tus recetas"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOW2NDSKILLRANK_MENUTEXT"] = "Include secondary skills"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOW2NDSKILLRANK_TEXT"] = "include secondary skill ranks"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOW2NDSKILLRANK_TOOLTIP"] = "If enabled, skill ranks are added for secondary skills; otherwise only for primary skills."
L["ARMORY_CMD_SET_SHOWACHIEVEMENTS_MENUTEXT"] = "Mostrar logros en links"
L["ARMORY_CMD_SET_SHOWACHIEVEMENTS_TEXT"] = "Mostrar personajes en logros linkeados"
L["ARMORY_CMD_SET_SHOWACHIEVEMENTS_TOOLTIP"] = "Si se habilita, los personajes que tienen o están en progreso con el logro linkeado en el chat son adicionados a esta tooltip"
L["ARMORY_CMD_SET_SHOWALTEQUIP_MENUTEXT"] = "Mostrar equipo alternativo"
L["ARMORY_CMD_SET_SHOWALTEQUIP_TEXT"] = "Muestra los slots de equipo alternativo"
L["ARMORY_CMD_SET_SHOWALTEQUIP_TOOLTIP"] = "Si esta habilitado, la figura de tu personaje mostrara otros ítems que puedan quedar en las ranuras de objeto."
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWCANLEARN_MENUTEXT"] = "Show 'learnable by' in tooltips"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWCANLEARN_TEXT"] = "show 'learnable by' in tooltips"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWCANLEARN_TOOLTIP"] = "If enabled, tooltips will show which character can learn the recipe or glyph."
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWCOUNTTOTAL_MENUTEXT"] = "Show item count totals"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWCOUNTTOTAL_TEXT"] = "include item count totals"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWCOUNTTOTAL_TOOLTIP"] = "If enabled a grand total will be added to the item counts."
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWCRAFTERS_MENUTEXT"] = "Show crafters in tooltips"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWCRAFTERS_TEXT"] = "show crafters in tooltips"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWCRAFTERS_TOOLTIP"] = "If enabled, item tooltips will show which character can craft that item."
L["ARMORY_CMD_SET_SHOWEQCTOOLTIPS_MENUTEXT"] = "Muestrar tooltips de comparación"
L["ARMORY_CMD_SET_SHOWEQCTOOLTIPS_TEXT"] = "Mostrar tooltips de comparación de equipo"
L["ARMORY_CMD_SET_SHOWEQCTOOLTIPS_TOOLTIP"] = "Si se habilita, las tooltips de comparación se mostraran cuando la tecla ALT es presionada mientras una tooltip de equipo de juego es visible."
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWGEARSETS_MENUTEXT"] = "Show gear sets in tooltip"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWGEARSETS_TEXT"] = "show equipment set names in tooltips"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWGEARSETS_TOOLTIP"] = "If enabled and equipment belongs to a gear set, the name of the set will be shown in its tooltip."
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWGEMS_MENUTEXT"] = "Show gemming details"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWGEMS_TEXT"] = "show socket gemming details in tooltips"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWGEMS_TOOLTIP"] = "If enabled, the color of the socket and the name of the gem will be added to the item tooltip."
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWHASSKILL_MENUTEXT"] = "Show 'attainable by' in tooltips"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWHASSKILL_TEXT"] = "show 'attainable by' in tooltips"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWHASSKILL_TOOLTIP"] = "If enabled, tooltips will show which character will eventually be able to learn the recipe or glyph."
L["ARMORY_CMD_SET_SHOWITEMCOUNT_MENUTEXT"] = "Mostrar contador de tooltip de objeto"
L["ARMORY_CMD_SET_SHOWITEMCOUNT_TEXT"] = "Mostrar contador de objeto en tooltips"
L["ARMORY_CMD_SET_SHOWITEMCOUNT_TOOLTIP"] = "Si esta habilitado, tooltips de objeto se mostraran con totales por personaje."
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWKNOWNBY_MENUTEXT"] = "Show 'known by' in tooltips"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWKNOWNBY_TEXT"] = "show 'known by' in tooltips"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWKNOWNBY_TOOLTIP"] = "If enabled, tooltips will show which character already knows the recipe or glyph."
L["ARMORY_CMD_SET_SHOWMINIMAP_MENUTEXT"] = "Mostrar botón en el minimapa"
L["ARMORY_CMD_SET_SHOWMINIMAP_TEXT"] = "Mostrar botón en el minimapa"
L["ARMORY_CMD_SET_SHOWMINIMAP_TOOLTIP"] = "Si se habilita, un botón de acceso fácil es adjuntado en el minimapa."
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWMMGLOBAL_MENUTEXT"] = "minimap button for all"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWMMGLOBAL_TEXT"] = "Use one minimap button for all characters"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWMMGLOBAL_TOOLTIP"] = "If enabled, one minimap button will be shown for all characters. If not, you'll have to enable or disable the minimap button for each character individually."
L["ARMORY_CMD_SET_SHOWQUESTALTS_MENUTEXT"] = "Mostrar Alts en las misiones linkeadas"
L["ARMORY_CMD_SET_SHOWQUESTALTS_TEXT"] = "Mostrar personajes en la misiones linkeadas"
L["ARMORY_CMD_SET_SHOWQUESTALTS_TOOLTIP"] = "Si se habilita, los personajes que están en la misión linkeada en el chat serán agregados a la tooltip."
L["ARMORY_CMD_SET_SHOWSHAREMSG_MENUTEXT"] = "Mostrar mensajes compartidos"
L["ARMORY_CMD_SET_SHOWSHAREMSG_TEXT"] = "Mostrar datos de mensajes compartidos"
L["ARMORY_CMD_SET_SHOWSHAREMSG_TOOLTIP"] = "Si se habilita, los mensajes serán escritos en el chat para proveer información acerca de los eventos de datos compartidos."
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWSKILLRANK_MENUTEXT"] = "Show skill ranks in tooltips"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWSKILLRANK_TEXT"] = "show skill ranks in tooltips"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWSKILLRANK_TOOLTIP"] = "If enabled, skill ranks are added to skill button tooltips."
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWSUMMARY_MENUTEXT"] = "Summary sheet"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWSUMMARY_TEXT"] = "show summary sheet"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWSUMMARY_TOOLTIP"] = "If enabled a character summary sheet will be show when hovering over the minimap or LDB button."
L["ARMORY_CMD_SET_SHOWUNEQUIP_MENUTEXT"] = "Mostrar alternativas no equipables"
L["ARMORY_CMD_SET_SHOWUNEQUIP_TEXT"] = "Mostrar alternativas no equipables"
L["ARMORY_CMD_SET_SHOWUNEQUIP_TOOLTIP"] = "Si se habilita, todos los objetos en el inventario que puedan ponerse en la ranura serán mostrados independientemente de los requisitos previos."
L["ARMORY_CMD_SET_SUCCESS"] = "1$s colocado en %2$s"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SUMMARYDELAY_TEXT"] = "Popup Delay"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SUMMARYDELAY_TOOLTIP"] = "Adjust the delay at which the summary will be shown."
--[[Translation missing --]]
L["ARMORY_CMD_SET_SYSTEMWARNINGS_MENUTEXT"] = "Enable system warnings"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SYSTEMWARNINGS_TEXT"] = "enable system warning messages"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SYSTEMWARNINGS_TOOLTIP"] = [=[If enabled, warning messages are displayed when something is wrong (e.g. the server is not returning any data).
 
You are strongly advised to keep this setting enabled. It is generally better to find the cause of the message and solve the issue. For example disabling the subclass and slot filters can be used as a workaround to prevent most trade skill update warnings. As a trade-off you'll lose some functionality though.]=]
--[[Translation missing --]]
L["ARMORY_CMD_SET_USECLASSCOLORS_MENUTEXT"] = "Use class colors"
--[[Translation missing --]]
L["ARMORY_CMD_SET_USECLASSCOLORS_TEXT"] = "use class colors for character names"
--[[Translation missing --]]
L["ARMORY_CMD_SET_USECLASSCOLORS_TOOLTIP"] = "If enabled, class colors are used when displaying character names."
--[[Translation missing --]]
L["ARMORY_CMD_SET_USEENCODING_MENUTEXT"] = "Prefer memory over CPU"
--[[Translation missing --]]
L["ARMORY_CMD_SET_USEENCODING_TEXT"] = "prefer memory usage over processing speed"
--[[Translation missing --]]
L["ARMORY_CMD_SET_USEENCODING_TOOLTIP"] = "If enabled, data will will stored in a binary encoded format taking up less memory but using more CPU for storage and retrieval. Enabling this option will decrease performance,"
--[[Translation missing --]]
L["ARMORY_CMD_SET_USEFACTIONFILTER_MENUTEXT"] = "Realm & faction filter"
--[[Translation missing --]]
L["ARMORY_CMD_SET_USEFACTIONFILTER_TEXT"] = "enable realm and faction filter"
--[[Translation missing --]]
L["ARMORY_CMD_SET_USEFACTIONFILTER_TOOLTIP"] = [=[If enabled, only characters on the current and connected realms and belonging to the current faction will be shown. This will also affect tooltip information.
Note that for item counts there is a separate realm and faction setting.]=]
--[[Translation missing --]]
L["ARMORY_CMD_SET_USEINPROGRESSCOLOR_MENUTEXT"] = "Use different color for 'in progress'"
--[[Translation missing --]]
L["ARMORY_CMD_SET_USEINPROGRESSCOLOR_TEXT"] = "colorize 'in progress' differently"
--[[Translation missing --]]
L["ARMORY_CMD_SET_USEINPROGRESSCOLOR_TOOLTIP"] = "If enabled, a different color will be used for achievements still in progress by a character."
--[[Translation missing --]]
L["ARMORY_CMD_SET_USEMAZIEL_MENUTEXT"] = "Use two stat panels"
--[[Translation missing --]]
L["ARMORY_CMD_SET_USEMAZIEL_TEXT"] = "hide talent build and professions"
--[[Translation missing --]]
L["ARMORY_CMD_SET_USEMAZIEL_TOOLTIP"] = "If enabled, the talent and profession frames will be replaced by a second stat panel."
--[[Translation missing --]]
L["ARMORY_CMD_SET_USEOVERLAY_MENUTEXT"] = "Enable character model overlay"
--[[Translation missing --]]
L["ARMORY_CMD_SET_USEOVERLAY_TEXT"] = "replace character model with Armory layout"
--[[Translation missing --]]
L["ARMORY_CMD_SET_USEOVERLAY_TOOLTIP"] = "If enabled, Armory's layout will replace the character model when the character frame is collapsed."
--[[Translation missing --]]
L["ARMORY_CMD_SET_WARNINGSOUND_MENUTEXT"] = "Warning sound"
--[[Translation missing --]]
L["ARMORY_CMD_SET_WARNINGSOUND_TEXT"] = "warning message sound"
--[[Translation missing --]]
L["ARMORY_CMD_SET_WARNINGSOUND_TOOLTIP"] = "Select a sound to play when an automated warning or error message is displayed in the chat frame."
--[[Translation missing --]]
L["ARMORY_CMD_SET_WEEKLYRESET_MENUTEXT"] = "Weekly reset"
--[[Translation missing --]]
L["ARMORY_CMD_SET_WEEKLYRESET_TEXT"] = "weekly server reset"
--[[Translation missing --]]
L["ARMORY_CMD_SET_WEEKLYRESET_TOOLTIP"] = "Select the day on which the server resets weekly (Tuesday for US servers and Wednesday for EU servers)."
L["ARMORY_CMD_SET_WINDOWSEARCH_MENUTEXT"] = "Mostrar resultados en la ventana"
L["ARMORY_CMD_SET_WINDOWSEARCH_TEXT"] = "Mostrar resultados del comando de búsqueda en una ventana dedicada"
L["ARMORY_CMD_SET_WINDOWSEARCH_TOOLTIP"] = "Si se habilita, los resultados del comando búsqueda serán presentados en una ventana por separado, de otra manera los resultados se verán en la ventana del chat."
L["ARMORY_CMD_TOGGLE"] = "Ocultar Armory habilitado o deshabilitado"
L["ARMORY_CMD_USAGE"] = "Uso"
--[[Translation missing --]]
L["ARMORY_COOLDOWN_AVAILABLE"] = "Cooldown of '%1$s' is available again for %2$s (%3$s)."
--[[Translation missing --]]
L["ARMORY_COOLDOWN_WARNING"] = "%s in %d |4minute:minutes;"
--[[Translation missing --]]
L["ARMORY_CRAFTABLE_BY"] = "Craftable by"
L["ARMORY_DB_INCOMPATIBLE"] = [=[La base de datos no es compatible con esta versión de Armory y será limpiada.
Necesitaras iniciar sesión con cada personaje para reconstruir la base de datos.]=]
L["ARMORY_DELETE_UNIT"] = "Estas seguro que quieres remover %s de la base de datos?"
L["ARMORY_DELETE_UNIT_HINT"] = "Tooltip de retrato"
L["ARMORY_EQUIPMENT"] = "Equipo"
--[[Translation missing --]]
L["ARMORY_EQUIPPED"] = "Equipped"
--[[Translation missing --]]
L["ARMORY_ERROR"] = "ERROR"
--[[Translation missing --]]
L["ARMORY_EVENT_WARNING"] = "%s starts in %d |4minute:minutes;"
L["ARMORY_EXPIRATION_LABEL"] = "Expiración "
L["ARMORY_EXPIRATION_SUBTEXT"] = "Esta opción habilita cambiar en el comportamiento de la verificación de expiración del buzón de correo."
L["ARMORY_EXPIRATION_TITLE"] = "Expiración de correo"
L["ARMORY_EXTENDED"] = "Extendida"
L["ARMORY_FILTER_ALL"] = "Seleccionar todos"
L["ARMORY_FILTER_CLEAR"] = "Limpiar selección "
L["ARMORY_FILTER_DISABLE"] = "Deshabilitar filtros"
L["ARMORY_FILTER_ENABLE"] = "Habilitar filtros"
L["ARMORY_FILTER_LABEL"] = "Filtros: %s"
L["ARMORY_FILTER_TOOLTIP"] = "Botón de tooltip"
L["ARMORY_FIND_BUTTON"] = "Buscar el botón de Armory"
L["ARMORY_FIND_LABEL"] = "Búsqueda"
L["ARMORY_FIND_SUBTEXT"] = "Esta opción te permite cambiar el comportamiento del comando busqueda"
L["ARMORY_FIND_TITLE"] = "Búsqueda en la base de datos"
L["ARMORY_FONT_COLOR"] = "Color de la fuente"
--[[Translation missing --]]
L["ARMORY_FULLY_RESTED"] = "Fully rested in: %s"
L["ARMORY_GLOBAL"] = "Global"
L["ARMORY_GLYPH"] = "Glifo"
L["ARMORY_IGNORE_REASON_COMBAT"] = "Deshabilitar compartir mientras estas en combate"
L["ARMORY_IGNORE_REASON_INSTANCE"] = "Deshabilitar compartir mientras estas en una instancia"
L["ARMORY_IGNORE_REASON_SHARING"] = "Deshabilitar compartir "
L["ARMORY_IGNORE_REASON_VERSION"] = "Versión del protocolo no soportada"
--[[Translation missing --]]
L["ARMORY_INFO"] = "INFO"
--[[Translation missing --]]
L["ARMORY_INVALID_ITEM"] = "Invalid item, please rescan."
L["ARMORY_INVENTORY_BAGLAYOUT"] = "Usar patrón de bolsa"
L["ARMORY_INVENTORY_BAGLAYOUT_TOOLTIP"] = "Mostrar contenedores concordando con el patrón actual."
L["ARMORY_INVENTORY_ICONVIEW"] = "Vista del icono"
L["ARMORY_INVENTORY_ICONVIEW_TOOLTIP"] = "Vista estándar"
L["ARMORY_INVENTORY_LISTVIEW"] = "Vista de lista"
L["ARMORY_INVENTORY_LISTVIEW_TOOLTIP"] = "Vista Avanzada"
L["ARMORY_INVENTORY_SEARCH_ALL"] = "Todos los personajes"
L["ARMORY_INVENTORY_SEARCH_ALL_TOOLTIP"] = "Seleccionar todos los objetos en inventario de todos los personajes en la base de datos."
L["ARMORY_INVENTORY_SEARCH_TEXT_TOOLTIP"] = [=[escribe tu criterio de filtros

Nota que puedes filtrar por calidad al escribir  '=' seguido de %s, %s, %s, %s, %s, %s, %s o %s o sus respectivos identificadores numéricos 0-7 (ejem. '=4' para ítems épicos).]=]
--[[Translation missing --]]
L["ARMORY_KNOWN_BY"] = "Known by"
--[[Translation missing --]]
L["ARMORY_LINK_HINT"] = "Shift-click to link"
L["ARMORY_LINK_TRADESKILL_TOOLTIP"] = "Shift-click abre tu profesión."
L["ARMORY_LOOKUP_BUTTON"] = "Retroalimentar"
L["ARMORY_LOOKUP_CHARACTER"] = "Retroalimentar personaje"
L["ARMORY_LOOKUP_CHARACTER_SEARCH_TOOLTIP"] = [=[Escribe tu criterios de filtro

 Nota que puede ser el nombre de un Alt de alguien.]=]
L["ARMORY_LOOKUP_DETAIL"] = "Click para detalles"
L["ARMORY_LOOKUP_DISABLED"] = "Compartir datos esta deshabilitado."
L["ARMORY_LOOKUP_IGNORED"] = "Requerimiento ignorado (razón: %s)"
--[[Translation missing --]]
L["ARMORY_LOOKUP_ITEM"] = "Lookup item"
L["ARMORY_LOOKUP_NODETAIL"] = "No hay detalles disponibles"
--[[Translation missing --]]
L["ARMORY_LOOKUP_NOT_CACHED"] = "Item information missing; please retry"
--[[Translation missing --]]
L["ARMORY_LOOKUP_PLAYER_HINT"] = [=[Shift-click for player info
Right-click to whisper]=]
L["ARMORY_LOOKUP_QUEST"] = "Retroalimentar Misiones"
L["ARMORY_LOOKUP_QUEST_AREA"] = "Área de Misión"
L["ARMORY_LOOKUP_QUEST_NAME"] = "Nombre de la Misión "
L["ARMORY_LOOKUP_QUEST_SEARCH_TOOLTIP"] = [=[Escribe tu criterio de filtro.

 Nota que puedes requerir por personajes que tienen misiones en cierta área seleccionado la correspondiente opción en la lista.]=]
L["ARMORY_LOOKUP_REALM_ALIAS"] = "Revisado"
L["ARMORY_LOOKUP_REQUEST_DETAIL"] = "Datos requeridos: %s"
L["ARMORY_LOOKUP_REQUEST_RECEIVED"] = "Requerimiento de compartición de datos recibida de %s"
L["ARMORY_LOOKUP_REQUEST_SENT"] = "Requerimiento enviado a %s"
L["ARMORY_LOOKUP_RESPONSE_RECEIVED"] = "Datos recibidos de %s"
L["ARMORY_LOOKUP_RESPONSE_SENT"] = "Respuesta enviada a %s"
L["ARMORY_LOOKUP_SEARCH_EXACT"] = "Coincidencia exacta"
L["ARMORY_LOOKUP_SKILL"] = "Buscar recetas"
L["ARMORY_LOOKUP_SKILL_SEARCH_TOOLTIP"] = [=[Escribe tus criterios de filtro.

 Nombres de personaje buscados pueden ser clickeados para acceder a su ventana de habilidades.
 Nota que puedes requerir la lista de recetas completa tan solo escribiendo un asterisco (*).]=]
--[[Translation missing --]]
L["ARMORY_MAIL_COUNT_WARNING1"] = "The inbox still contains %d |4mail:mails; that couldn't be scanned."
--[[Translation missing --]]
L["ARMORY_MAIL_COUNT_WARNING2"] = "%1$s (%2$s) has %d |4mail:mails; that couldn't be scanned."
--[[Translation missing --]]
L["ARMORY_MAIL_COUNT_WARNING3"] = "Unknown sender detected. Please reopen your mail to force a rescan if this is unexpected."
--[[Translation missing --]]
L["ARMORY_MAIL_ITEM_COUNT"] = "Number of items:"
--[[Translation missing --]]
L["ARMORY_MAIL_LAST_VISIT"] = "Last visit:"
--[[Translation missing --]]
L["ARMORY_MAIL_REMAINING"] = "Mail remaining:"
--[[Translation missing --]]
L["ARMORY_MAIL_VISIT_WARNING"] = "%1$s (%2$s) hasn't visited the mailbox for %3$s. Please log in to check your inbox."
L["ARMORY_MINIMAP_LABEL"] = "Minimapa"
L["ARMORY_MINIMAP_SUBTEXT"] = "Esta opción controla si se muestra el botón en el minimapa."
L["ARMORY_MINIMAP_TITLE"] = "Botón de Armory en el minimapa"
L["ARMORY_MISC_LABEL"] = "Otras opciones"
L["ARMORY_MISC_SUBTEXT"] = "Estas opciones permiten cambiar varias configuraciones."
L["ARMORY_MISC_TITLE"] = "Otras opciones"
L["ARMORY_MODULES_LABEL"] = "Modulos"
L["ARMORY_MODULES_SUBTEXT"] = "Estas opciones permiten seleccionar que módulos estarán activos."
L["ARMORY_MODULES_TITLE"] = "Módulos de Armory"
L["ARMORY_MONEY_TOTAL"] = "total de %1$s %2$s :"
--[[Translation missing --]]
L["ARMORY_NO_DATA"] = "No data available"
--[[Translation missing --]]
L["ARMORY_OPEN_HINT"] = "Click to open"
--[[Translation missing --]]
L["ARMORY_PANDARIA_GEM_RESEARCH"] = "Pandaria Gem Research"
L["ARMORY_QUEST_TOOLTIP_LABEL"] = "Alts en esta Misión:"
L["ARMORY_RECIPE"] = "Receta"
--[[Translation missing --]]
L["ARMORY_RECIPE_WARNING"] = [=[Recipe %s not found in LibRecipes. Trying to make an educated guess.
Please check with '/armory find skill ...' to be sure.]=]
L["ARMORY_REPUTATION_SUMMARY"] = "%1$s - %2$s (quedan %3$d/%4$d, %5$d)"
L["ARMORY_SEARCHING"] = "Buscando..."
--[[Translation missing --]]
L["ARMORY_SELECT_UNIT_HINT"] = "Left-click to select this character."
L["ARMORY_SHARE_DOWNLOAD_LOADERROR"] = "No se puede cargar %1$s; razón: %2$s"
L["ARMORY_SHARE_LABEL"] = "Compartiendo"
L["ARMORY_SHARE_SUBTEXT1"] = "Estas opciones definen como compartes tus datos con otros usuarios de Armory. Nota que estas opciones esta basadas por personaje."
L["ARMORY_SHARE_SUBTEXT2"] = "Las siguiente opciones serán configuradas a nivel global."
L["ARMORY_SHARE_TITLE"] = "Compartiendo datos"
L["ARMORY_SHORTDATE_FORMAT"] = "ARMORY_SHORTDATE_FORMAT"
L["ARMORY_SLASH_ALTERNATIVES"] = "/ar"
--[[Translation missing --]]
L["ARMORY_SOCIAL_ADD_TOOLTIP"] = "Shift-click to add to your current list."
L["ARMORY_SUBTEXT"] = "Estas opciones permiten modificar el comportamiento de Armory."
--[[Translation missing --]]
L["ARMORY_SUMMARY_LABEL"] = "Summary"
--[[Translation missing --]]
L["ARMORY_SUMMARY_SUBTEXT1"] = "These options allow you to change Armory's character summary sheet."
--[[Translation missing --]]
L["ARMORY_SUMMARY_SUBTEXT2"] = "Select the information to show."
--[[Translation missing --]]
L["ARMORY_SUMMARY_TITLE"] = "Summary Options"
L["ARMORY_TALENTS"] = "Especialización de talentos:"
L["ARMORY_TOOLTIP_HINT1"] = "Click Izquierdo para ocultar Armory"
L["ARMORY_TOOLTIP_HINT2"] = "Click derecho para opciones"
L["ARMORY_TOOLTIP_LABEL"] = "Tooltip"
L["ARMORY_TOOLTIP_SUBTEXT"] = "Estas opciones permiten agregar información a las tooltips."
L["ARMORY_TOOLTIP_TITLE"] = "Tooltip de encantamiento"
L["ARMORY_TOOLTIP1"] = "Personaje:"
L["ARMORY_TOOLTIP2"] = "Reino:"
--[[Translation missing --]]
L["ARMORY_TOTAL"] = "Total: %d"
L["ARMORY_TRADE_ALCHEMY"] = "Alquimia"
L["ARMORY_TRADE_BLACKSMITHING"] = "Herrería"
L["ARMORY_TRADE_COOKING"] = "Cocina"
L["ARMORY_TRADE_ENCHANTING"] = "Encantamiento"
L["ARMORY_TRADE_ENGINEERING"] = "Ingeniería"
L["ARMORY_TRADE_FIRST_AID"] = "Primeros auxilios"
L["ARMORY_TRADE_FISHING"] = "Pesca"
L["ARMORY_TRADE_HERBALISM"] = "Herbalísmo"
L["ARMORY_TRADE_INSCRIPTION"] = "Inscripción "
L["ARMORY_TRADE_JEWELCRAFTING"] = "Joyería"
L["ARMORY_TRADE_LEATHERWORKING"] = "Peletería"
L["ARMORY_TRADE_MINING"] = "Minería "
L["ARMORY_TRADE_POISONS"] = "Venenos "
L["ARMORY_TRADE_SKILLS"] = "Profesiones primarias"
L["ARMORY_TRADE_SKINNING"] = "Desuello"
L["ARMORY_TRADE_TAILORING"] = "Sastrería"
--[[Translation missing --]]
L["ARMORY_TRADE_UPDATE_FAILED"] = "Profession data incomplete. Please reopen and close your profession window again."
L["ARMORY_TRADE_UPDATE_WARNING"] = "Datos de profesión no salvados. Por favor usa el botón cerrar para ejecutar una actualización."
L["ARMORY_TRADESKILL_SEARCH_TEXT_TOOLTIP"] = [=[Escribe tu criterio para filtrar.

Nota que puedes escribir por ejemplo '10', '~10' or '10-20' para filtrar el nivel de la receta.]=]
L["ARMORY_TRANSMUTE"] = "Transmutar"
--[[Translation missing --]]
L["ARMORY_UPDATE_SUSPENDED"] = "suspended"
--[[Translation missing --]]
L["ARMORY_VOID_STORAGE_ABBR"] = "Void"
--[[Translation missing --]]
L["ARMORY_WARNING"] = "WARNING"
L["ARMORY_WHAT"] = "Que"
L["ARMORY_WHERE"] = "Donde"
L["ARMORY_WHO"] = "Quien"
--[[Translation missing --]]
L["ARMORY_WILL_LEARN"] = "Attainable by"
--[[Translation missing --]]
L["ARMORY_XP_SUMMARY"] = "Level %1$d (%2$s) %3$d XP to go, %4$s rested"
--[[Translation missing --]]
L["BINDING_NAME_ARMORY_ACHIEVEMENT"] = "Open achievement pane"
--[[Translation missing --]]
L["BINDING_NAME_ARMORY_CHARACTER"] = "Open character frame"
--[[Translation missing --]]
L["BINDING_NAME_ARMORY_CURRENCY"] = "Open currency frame"
--[[Translation missing --]]
L["BINDING_NAME_ARMORY_INVENTORY"] = "Open inventory"
--[[Translation missing --]]
L["BINDING_NAME_ARMORY_PET"] = "Open pet frame"
--[[Translation missing --]]
L["BINDING_NAME_ARMORY_PVP"] = "Open PVP frame"
--[[Translation missing --]]
L["BINDING_NAME_ARMORY_QUEST"] = "Open quest log"
--[[Translation missing --]]
L["BINDING_NAME_ARMORY_RAID"] = "Open raid frame"
--[[Translation missing --]]
L["BINDING_NAME_ARMORY_REPUTATION"] = "Open reputation frame"
--[[Translation missing --]]
L["BINDING_NAME_ARMORY_SOCIAL"] = "Open social pane"
--[[Translation missing --]]
L["BINDING_NAME_ARMORY_SPELLBOOK"] = "Open spellbook"
--[[Translation missing --]]
L["BINDING_NAME_ARMORY_TALENT"] = "Open talent frame"
L["BINDING_NAME_ARMORY_TOGGLE"] = "Ocultar Armory"
--[[Translation missing --]]
L["BINDING_NAME_ARMORY_TRADESKILL1"] = "Open primary profession 1"
--[[Translation missing --]]
L["BINDING_NAME_ARMORY_TRADESKILL2"] = "Open primary profession 2"
L["BINDING_NAME_CURRENT_CHARACTER"] = "Seleccionar personaje actual"
L["BINDING_NAME_FIND"] = "Ocultar búsqueda en la base de datos"
L["BINDING_NAME_LOOKUP"] = "Ocultar Busqueda"
L["BINDING_NAME_NEXT_CHARACTER"] = "Seleccionar personaje siguiente"
L["BINDING_NAME_PREVIOUS_CHARACTER"] = "Seleccionar personaje previo"

