--[[

    Please do NOT edit this file but go to http://wow.curseforge.com/addons/armory/localization/ instead.

    Original translators: MegaKSVS, alex_n
    
    The contents of this file will be generated automatically.
    
]]--

local L = LibStub("AceLocale-3.0"):NewLocale("Armory", "ruRU");
if ( not L ) then 
    return;
end

--@localization(locale="ruRU", format="lua_additive_table", namespace="Armory", handle-unlocalized="english", handle-subnamespaces="none")@
