--[[

    Please do NOT edit this file but go to http://wow.curseforge.com/addons/armory/localization/ instead.
    
    The contents of this file will be generated automatically.
    
]]--

local L = LibStub("AceLocale-3.0"):NewLocale("Armory", "zhTW");
if ( not L ) then 
    return;
end

-- Armory
L["ARMORY_ALTS"] = "分身"
--[[Translation missing --]]
L["ARMORY_BAGS"] = "Bags"
L["ARMORY_BANK_CONTAINER_NAME"] = "銀行"
--[[Translation missing --]]
L["ARMORY_BONUS_PATTERN"] = "(.+) Bonus"
--[[Translation missing --]]
L["ARMORY_BUZZ_WORDS"] = [=[of
the]=]
--[[Translation missing --]]
L["ARMORY_BY_DATE"] = "View by date"
--[[Translation missing --]]
L["ARMORY_BY_GROUP"] = "View by group"
--[[Translation missing --]]
L["ARMORY_CAN_LEARN"] = "Learnable by"
--[[Translation missing --]]
L["ARMORY_CHECK_CD_NONE"] = "No cooldowns found"
L["ARMORY_CHECK_MAIL_DISABLED"] = "信件過期檢查功能被關閉。"
L["ARMORY_CHECK_MAIL_MESSAGE"] = "%1$s (%2$s) 信箱中的 '%3$s' 將在 %4$s 天後過期！"
L["ARMORY_CHECK_MAIL_NONE"] = "信箱中沒有即將過期的物品。"
L["ARMORY_CHECK_MAIL_POPUP"] = "信箱中有即將過期的物品，請使用 '/ar check' 來獲得更多資訊。"
--[[Translation missing --]]
L["ARMORY_CMD_CHECK"] = "check"
--[[Translation missing --]]
L["ARMORY_CMD_CHECK_INVALID"] = "Specify the number of days to check or none for default."
L["ARMORY_CMD_CHECK_MENUTEXT"] = "檢查是否有過期信件"
L["ARMORY_CMD_CHECK_TEXT"] = "檢查信箱中是否有即將過期的物品"
--[[Translation missing --]]
L["ARMORY_CMD_CHECKCD"] = "cooldown|cd"
--[[Translation missing --]]
L["ARMORY_CMD_CHECKCD_TEXT"] = "check tradeskill cooldowns"
--[[Translation missing --]]
L["ARMORY_CMD_CONFIG"] = "config"
L["ARMORY_CMD_CONFIG_TEXT"] = "打開設定介面"
--[[Translation missing --]]
L["ARMORY_CMD_DELETE"] = "delete"
--[[Translation missing --]]
L["ARMORY_CMD_DELETE_ALL"] = "all"
L["ARMORY_CMD_DELETE_ALL_MSG"] = "Armory資料庫已全部清空。"
L["ARMORY_CMD_DELETE_ALL_TEXT"] = "刪除整個資料庫"
--[[Translation missing --]]
L["ARMORY_CMD_DELETE_CHAR"] = "char"
--[[Translation missing --]]
L["ARMORY_CMD_DELETE_CHAR_MSG"] = "Armory entry for '%1$s' in realm '%2$s' has been removed."
L["ARMORY_CMD_DELETE_CHAR_NOT_FOUND"] = "沒有找到在 '%2$s' 伺服器中的 '%1$s' 角色！"
--[[Translation missing --]]
L["ARMORY_CMD_DELETE_CHAR_PARAMS_TEXT"] = "[name] [realm]"
L["ARMORY_CMD_DELETE_CHAR_TEXT"] = "刪除一個角色"
--[[Translation missing --]]
L["ARMORY_CMD_DELETE_REALM"] = "realm"
L["ARMORY_CMD_DELETE_REALM_MSG"] = "'%s' 伺服器已全部清空。"
--[[Translation missing --]]
L["ARMORY_CMD_DELETE_REALM_NOT_FOUND"] = "Armory realm '%s' not found!"
L["ARMORY_CMD_DELETE_REALM_PARAMS_TEXT"] = "[名稱]"
--[[Translation missing --]]
L["ARMORY_CMD_DELETE_REALM_TEXT"] = "delete all realm data"
--[[Translation missing --]]
L["ARMORY_CMD_DOWNLOAD"] = "download"
L["ARMORY_CMD_DOWNLOAD_TEXT"] = "向公會成員取得配方資訊"
--[[Translation missing --]]
L["ARMORY_CMD_FIND"] = "find"
--[[Translation missing --]]
L["ARMORY_CMD_FIND_ALL"] = "all"
L["ARMORY_CMD_FIND_FOUND"] = "共發現： %d"
--[[Translation missing --]]
L["ARMORY_CMD_FIND_GLYPH"] = "glyph"
--[[Translation missing --]]
L["ARMORY_CMD_FIND_GLYPH_TOOLTIP"] = "Use '?' or '%s' to find glyphs you haven't learned yet."
--[[Translation missing --]]
L["ARMORY_CMD_FIND_INVENTORY"] = "inventory"
--[[Translation missing --]]
L["ARMORY_CMD_FIND_ITEM"] = "item"
L["ARMORY_CMD_FIND_MENUTEXT"] = "搜尋資料庫"
L["ARMORY_CMD_FIND_NOT_FOUND"] = "未發現"
L["ARMORY_CMD_FIND_PARAMS_TEXT"] = "[關鍵字]"
--[[Translation missing --]]
L["ARMORY_CMD_FIND_QUEST"] = "quest"
L["ARMORY_CMD_FIND_QUEST_REWARD"] = "任務獎勵"
--[[Translation missing --]]
L["ARMORY_CMD_FIND_SKILL"] = "skill"
--[[Translation missing --]]
L["ARMORY_CMD_FIND_SPELL"] = "spell"
L["ARMORY_CMD_FIND_TEXT"] = "在本地資料庫中搜尋"
--[[Translation missing --]]
L["ARMORY_CMD_HELP"] = "help"
L["ARMORY_CMD_HELP_TEXT"] = "顯示這個指令幫助清單"
--[[Translation missing --]]
L["ARMORY_CMD_LOOKUP"] = "lookup"
--[[Translation missing --]]
L["ARMORY_CMD_LOOKUP_MENUTEXT"] = "Lookup information"
L["ARMORY_CMD_LOOKUP_TEXT"] = "搜尋來自其他玩家的資訊"
--[[Translation missing --]]
L["ARMORY_CMD_RESET"] = "reset"
--[[Translation missing --]]
L["ARMORY_CMD_RESET_FRAME"] = "frames"
L["ARMORY_CMD_RESET_FRAME_MENUTEXT"] = "重置視窗位置"
--[[Translation missing --]]
L["ARMORY_CMD_RESET_FRAME_SUCCESS"] = "frames reset"
L["ARMORY_CMD_RESET_FRAME_TEXT"] = "將視窗位置還原到原始位置"
--[[Translation missing --]]
L["ARMORY_CMD_RESET_SETTINGS"] = "settings"
--[[Translation missing --]]
L["ARMORY_CMD_RESET_SETTINGS_SUCCESS"] = "settings reset"
--[[Translation missing --]]
L["ARMORY_CMD_RESET_SETTINGS_TEXT"] = "set all settings back to their defaults"
--[[Translation missing --]]
L["ARMORY_CMD_SET_ALTCLICKSEARCH_MENUTEXT"] = "Search Alt-clicked link"
--[[Translation missing --]]
L["ARMORY_CMD_SET_ALTCLICKSEARCH_TEXT"] = "start a search when Alt-clicking a chat link"
--[[Translation missing --]]
L["ARMORY_CMD_SET_ALTCLICKSEARCH_TOOLTIP"] = "If enabled, the find command will be invoked while holding down the Alt key and clicking a searchable link in the chat frame."
--[[Translation missing --]]
L["ARMORY_CMD_SET_CHECKBUTTON_MENUTEXT"] = "Hide Armory button"
--[[Translation missing --]]
L["ARMORY_CMD_SET_CHECKBUTTON_TEXT"] = "hide the Armory check button on the character frame"
--[[Translation missing --]]
L["ARMORY_CMD_SET_CHECKBUTTON_TOOLTIP"] = "If enabled, the Armory check button in the lower left corner of the character frame will not be shown."
--[[Translation missing --]]
L["ARMORY_CMD_SET_CHECKCOOLDOWNS_MENUTEXT"] = "Check available cooldowns"
--[[Translation missing --]]
L["ARMORY_CMD_SET_CHECKCOOLDOWNS_TEXT"] = "check available cooldowns on startup"
--[[Translation missing --]]
L["ARMORY_CMD_SET_CHECKCOOLDOWNS_TOOLTIP"] = "If enabled, tradeskill cooldowns that became available while you were offline will be displayed when you log in."
--[[Translation missing --]]
L["ARMORY_CMD_SET_COLLAPSE_MENUTEXT"] = "Collapse character frame"
--[[Translation missing --]]
L["ARMORY_CMD_SET_COLLAPSE_TEXT"] = "collapse the character frame"
--[[Translation missing --]]
L["ARMORY_CMD_SET_COLLAPSE_TOOLTIP"] = "If enabled, the character frame will be collapsed when Armory's layout is active."
--[[Translation missing --]]
L["ARMORY_CMD_SET_COOLDOWNEVENTS_MENUTEXT"] = "Include tradeskill cooldowns"
--[[Translation missing --]]
L["ARMORY_CMD_SET_COOLDOWNEVENTS_TEXT"] = "include tradeskill cooldowns in event list"
--[[Translation missing --]]
L["ARMORY_CMD_SET_COOLDOWNEVENTS_TOOLTIP"] = "If enabled, tradeskill cooldowns will be included in Armory's event list."
L["ARMORY_CMD_SET_COUNTALL_MENUTEXT"] = "統計數字將包含所有伺服器"
L["ARMORY_CMD_SET_COUNTALL_TEXT"] = "統計數字將包含所有伺服器"
--[[Translation missing --]]
L["ARMORY_CMD_SET_COUNTALL_TOOLTIP"] = "If enabled, totals are shown for all realms; otherwise only for the current and connected realms."
--[[Translation missing --]]
L["ARMORY_CMD_SET_COUNTPERSLOT_MENUTEXT"] = "Totals per bag/bank slot"
--[[Translation missing --]]
L["ARMORY_CMD_SET_COUNTPERSLOT_TEXT"] = "show item counts per bag/bank slot"
--[[Translation missing --]]
L["ARMORY_CMD_SET_COUNTPERSLOT_TOOLTIP"] = "If enabled, items counts are shown per bag or bank slot, where slot '0' represents the backpack or bank itself."
--[[Translation missing --]]
L["ARMORY_CMD_SET_COUNTXFACTION_MENUTEXT"] = "Include all factions in counts"
--[[Translation missing --]]
L["ARMORY_CMD_SET_COUNTXFACTION_TEXT"] = "include item counts for all factions"
--[[Translation missing --]]
L["ARMORY_CMD_SET_COUNTXFACTION_TOOLTIP"] = "If enabled, totals are shown for all factions; otherwise only for the current faction."
--[[Translation missing --]]
L["ARMORY_CMD_SET_DEFAULTSEARCH_MENUTEXT"] = "Default search domain"
--[[Translation missing --]]
L["ARMORY_CMD_SET_DEFAULTSEARCH_TEXT"] = "default domain"
--[[Translation missing --]]
L["ARMORY_CMD_SET_DEFAULTSEARCH_TOOLTIP"] = "The search domain to use when none is specified."
--[[Translation missing --]]
L["ARMORY_CMD_SET_ENABLED_MENUTEXT"] = "Enable character"
--[[Translation missing --]]
L["ARMORY_CMD_SET_ENABLED_TEXT"] = "include this character in Armory"
--[[Translation missing --]]
L["ARMORY_CMD_SET_ENABLED_TOOLTIP"] = [=[If enabled, Armory will perform data collection for the current character.
Note that changing this option will result in a UI reload.]=]
--[[Translation missing --]]
L["ARMORY_CMD_SET_EVENTLOCALTIME_MENUTEXT"] = "Use local time for events"
--[[Translation missing --]]
L["ARMORY_CMD_SET_EVENTLOCALTIME_TEXT"] = "use local time in event list"
--[[Translation missing --]]
L["ARMORY_CMD_SET_EVENTLOCALTIME_TOOLTIP"] = "If enabled, local time is used in the event list; otherwise the realm time."
--[[Translation missing --]]
L["ARMORY_CMD_SET_EVENTWARNINGS_MENUTEXT"] = "Event notifications"
--[[Translation missing --]]
L["ARMORY_CMD_SET_EVENTWARNINGS_TEXT"] = "enable event notifications"
--[[Translation missing --]]
L["ARMORY_CMD_SET_EVENTWARNINGS_TOOLTIP"] = "If enabled, you will be warned about confirmed events of your characters that are about to become due."
L["ARMORY_CMD_SET_EXPDAYS_INVALID"] = "%1$s 應該介於0(沒有警示)到 %2$d 天！"
L["ARMORY_CMD_SET_EXPDAYS_PARAMS_TEXT"] = "天數"
L["ARMORY_CMD_SET_EXPDAYS_TEXT"] = "物品過期的警示天數"
L["ARMORY_CMD_SET_EXPDAYS_TOOLTIP"] = "將按照指定的天數檢查信箱中的物品是否將過期(設定0為關閉警示)"
--[[Translation missing --]]
L["ARMORY_CMD_SET_EXTENDEDSEARCH_MENUTEXT"] = "Extended find"
--[[Translation missing --]]
L["ARMORY_CMD_SET_EXTENDEDSEARCH_TEXT"] = "look in tooltip text for matches when using find"
L["ARMORY_CMD_SET_EXTENDEDSEARCH_TOOLTIP"] = "勾選後，搜尋功能將會連同物品提示中的文字也一起檢查；否則只有名稱會被檢查。"
L["ARMORY_CMD_SET_EXTENDEDTRADE_MENUTEXT"] = "啟用專業技能篩選"
L["ARMORY_CMD_SET_EXTENDEDTRADE_TEXT"] = "啟用分支和空格的篩選"
--[[Translation missing --]]
L["ARMORY_CMD_SET_EXTENDEDTRADE_TOOLTIP"] = [=[If enabled, the professions can be filtered on subclass and/or item slots.
If you experience problems with other add-ons you can disable this feature to get a simple list that doesn't trigger any events (a categorized list will be available by shift-clicking the link button).]=]
--[[Translation missing --]]
L["ARMORY_CMD_SET_GLOBALSEARCH_MENUTEXT"] = "Global find"
--[[Translation missing --]]
L["ARMORY_CMD_SET_GLOBALSEARCH_TEXT"] = "search all realms when using the find command"
--[[Translation missing --]]
L["ARMORY_CMD_SET_GLOBALSEARCH_TOOLTIP"] = "If enabled, the find command will go through the entire database; otherwise only the current and connected realms will be searched."
--[[Translation missing --]]
L["ARMORY_CMD_SET_HIDELOGON_MENUTEXT"] = "Hide warning when logging in"
--[[Translation missing --]]
L["ARMORY_CMD_SET_HIDELOGON_TEXT"] = "don't show a warning when logging in"
--[[Translation missing --]]
L["ARMORY_CMD_SET_HIDELOGON_TOOLTIP"] = "If enabled, the warning will not be displayed when you log in."
--[[Translation missing --]]
L["ARMORY_CMD_SET_HIDEMMTOOLBAR_MENUTEXT"] = "Hide minimap button with toolbars"
--[[Translation missing --]]
L["ARMORY_CMD_SET_HIDEMMTOOLBAR_TEXT"] = "hide minimap button when Titan/FuBar is loaded"
--[[Translation missing --]]
L["ARMORY_CMD_SET_HIDEMMTOOLBAR_TOOLTIP"] = "If enabled, the minimap button will be hidden automatically when Titan or FuBar is loaded."
--[[Translation missing --]]
L["ARMORY_CMD_SET_IGNOREALTS_MENUTEXT"] = "Ignore mail from alts"
--[[Translation missing --]]
L["ARMORY_CMD_SET_IGNOREALTS_TEXT"] = "ignore warnings for mails from alts"
--[[Translation missing --]]
L["ARMORY_CMD_SET_IGNOREALTS_TOOLTIP"] = "If enabled, the popup warning will not be shown for expired mails that were sent (not returned) by one of your other characters. Note that characters must be known to Armory for this to work."
--[[Translation missing --]]
L["ARMORY_CMD_SET_LASTVIEWED_MENUTEXT"] = "Remember selection"
--[[Translation missing --]]
L["ARMORY_CMD_SET_LASTVIEWED_TEXT"] = "remember the last character viewed"
--[[Translation missing --]]
L["ARMORY_CMD_SET_LASTVIEWED_TOOLTIP"] = "If enabled, the last character selected will be stored between sessions."
--[[Translation missing --]]
L["ARMORY_CMD_SET_LDBLABEL_MENUTEXT"] = "Enable LDB label"
--[[Translation missing --]]
L["ARMORY_CMD_SET_LDBLABEL_TEXT"] = "enable LibDataBroker label display"
--[[Translation missing --]]
L["ARMORY_CMD_SET_LDBLABEL_TOOLTIP"] = "If enabled, a text label is shown in LibDataBroker display add-ons."
--[[Translation missing --]]
L["ARMORY_CMD_SET_MAILCHECKCOUNT_MENUTEXT"] = "Check for remaining mail"
--[[Translation missing --]]
L["ARMORY_CMD_SET_MAILCHECKCOUNT_TEXT"] = "check for remaining mail in the inbox"
--[[Translation missing --]]
L["ARMORY_CMD_SET_MAILCHECKCOUNT_TOOLTIP"] = "If enabled, a warning will be shown when not all mails were scanned because the inbox display limit has been exceeded."
--[[Translation missing --]]
L["ARMORY_CMD_SET_MAILCHECKVISIT_MENUTEXT"] = "Warn for unnoticed mail"
--[[Translation missing --]]
L["ARMORY_CMD_SET_MAILCHECKVISIT_TEXT"] = "include the last mailbox visit when checking for mail"
--[[Translation missing --]]
L["ARMORY_CMD_SET_MAILCHECKVISIT_TOOLTIP"] = "If enabled, a warning will be shown when a character's mailbox hasn't been opened for at least 30 minus expiration threshold number of days and therefore may contain mail without being noticed."
--[[Translation missing --]]
L["ARMORY_CMD_SET_MAILEXCLUDEVISIT_MENUTEXT"] = "Exclude this character's mailbox visit"
--[[Translation missing --]]
L["ARMORY_CMD_SET_MAILEXCLUDEVISIT_TEXT"] = "don't check this character's mailbox visit"
--[[Translation missing --]]
L["ARMORY_CMD_SET_MAILEXCLUDEVISIT_TOOLTIP"] = "If enabled, the current character's mailbox visit will be excluded from the check."
--[[Translation missing --]]
L["ARMORY_CMD_SET_MAILHIDECOUNT_MENUTEXT"] = "Hide remaining mail scan warning"
--[[Translation missing --]]
L["ARMORY_CMD_SET_MAILHIDECOUNT_TEXT"] = "don't show a warning when the mailbox is closed"
--[[Translation missing --]]
L["ARMORY_CMD_SET_MAILHIDECOUNT_TOOLTIP"] = "If enabled, the warning for remaining mail will not be shown when you close the mailbox."
--[[Translation missing --]]
L["ARMORY_CMD_SET_MMB_ANGLE_TEXT"] = "minimap button angle"
--[[Translation missing --]]
L["ARMORY_CMD_SET_MMB_GLOBAL_MENUTEXT"] = "position the button the same for all characters"
--[[Translation missing --]]
L["ARMORY_CMD_SET_MMB_GLOBAL_TEXT"] = "Use same position for all"
--[[Translation missing --]]
L["ARMORY_CMD_SET_MMB_GLOBAL_TOOLTIP"] = "If enabled, the angle and radius will be the same for all characters."
--[[Translation missing --]]
L["ARMORY_CMD_SET_MMB_RADIUS_TEXT"] = "minimap button radius"
--[[Translation missing --]]
L["ARMORY_CMD_SET_NOVALUE"] = "current setting: %s"
--[[Translation missing --]]
L["ARMORY_CMD_SET_NOVALUE_TEXT"] = "display current setting"
--[[Translation missing --]]
L["ARMORY_CMD_SET_OFF"] = "off"
--[[Translation missing --]]
L["ARMORY_CMD_SET_ON"] = "on"
--[[Translation missing --]]
L["ARMORY_CMD_SET_PAUSEINCOMBAT_MENUTEXT"] = "Pause in combat"
--[[Translation missing --]]
L["ARMORY_CMD_SET_PAUSEINCOMBAT_TEXT"] = "do not scan when in combat"
--[[Translation missing --]]
L["ARMORY_CMD_SET_PAUSEINCOMBAT_TOOLTIP"] = "If enabled Armory pauses scanning when you get into combat and resumes afterwards."
--[[Translation missing --]]
L["ARMORY_CMD_SET_PAUSEININSTANCE_MENUTEXT"] = "Remain paused in instance"
--[[Translation missing --]]
L["ARMORY_CMD_SET_PAUSEININSTANCE_TEXT"] = "do not resume when in an instance"
--[[Translation missing --]]
L["ARMORY_CMD_SET_PAUSEININSTANCE_TOOLTIP"] = "If enabled, getting out of combat in an instance will not process any postponed updates. Be aware that in this case item counts in tooltips will not be updated either."
--[[Translation missing --]]
L["ARMORY_CMD_SET_PERCHARACTER_MENUTEXT"] = "Remember per character"
--[[Translation missing --]]
L["ARMORY_CMD_SET_PERCHARACTER_TEXT"] = "remember individual settings"
--[[Translation missing --]]
L["ARMORY_CMD_SET_PERCHARACTER_TOOLTIP"] = "If enabled, the 'all characters' and 'last character' values will be stored on a per-character basis."
--[[Translation missing --]]
L["ARMORY_CMD_SET_RESTRICTIVESEARCH_MENUTEXT"] = "Restrictive find"
--[[Translation missing --]]
L["ARMORY_CMD_SET_RESTRICTIVESEARCH_TEXT"] = "don't include obtainable objects when using find"
--[[Translation missing --]]
L["ARMORY_CMD_SET_RESTRICTIVESEARCH_TOOLTIP"] = "If enabled, the find command will not consider obtainable objects, like rewards or craftables, as possible matches."
--[[Translation missing --]]
L["ARMORY_CMD_SET_SCALEONMOUSEWHEEL_MENUTEXT"] = "enable mouse wheel"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SCALEONMOUSEWHEEL_TEXT"] = "Enable mouse wheel"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SCALEONMOUSEWHEEL_TOOLTIP"] = "If enabled, scrolling the mouse wheel while hovering over the background of Armory's main frame will change the UI scale."
--[[Translation missing --]]
L["ARMORY_CMD_SET_SCANONENTER_MENUTEXT"] = "Force scan on login"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SCANONENTER_TEXT"] = "force a scan on the next login"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SCANONENTER_TOOLTIP"] = [=[If enabled Armory will forcibly update all accessible character data on the next login.
This setting will reset itself automatically.]=]
--[[Translation missing --]]
L["ARMORY_CMD_SET_SEARCHALL_MENUTEXT"] = "Remember 'all characters'"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SEARCHALL_TEXT"] = "remember the inventory 'all characters' setting"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SEARCHALL_TOOLTIP"] = "If enabled, the 'all characters' setting on the inventory list view will be stored between sessions."
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHAREALL_MENUTEXT"] = "Share all characters"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHAREALL_TEXT"] = "share information of all your characters"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHAREALL_TOOLTIP"] = "If enabled, information of all your characters is being shared; otherwise only your current character's information."
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHAREALT_MENUTEXT"] = "Reveal relationships"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHAREALT_TEXT"] = "Reveal relationship with other characters"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHAREALT_TOOLTIP"] = "If enabled, the relationship between the current character and your other characters will be visible (e.g. shown as alt). Disabling makes it a 'stand-alone' character."
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHARECHANNEL_MENUTEXT"] = "enable lookup channel"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHARECHANNEL_TEXT"] = "Enable custom channel"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHARECHANNEL_TOOLTIP"] = "If enabled, lookup requests can be sent through the provided channel which you can share with a specific group of players."
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHARECHARACTER_MENUTEXT"] = "Share character info"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHARECHARACTER_TEXT"] = "share your character info"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHARECHARACTER_TOOLTIP"] = "If enabled, other Armory users can inspect your equipment and talents."
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHAREGUILD_MENUTEXT"] = "Share guild characters"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHAREGUILD_TEXT"] = "share information of guild characters"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHAREGUILD_TOOLTIP"] = "If enabled, information of characters within the same guild is being shared."
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHAREINCOMBAT_MENUTEXT"] = "Share in combat"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHAREINCOMBAT_TEXT"] = "share while in combat"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHAREINCOMBAT_TOOLTIP"] = "If enabled, you will repond to queries while you are in combat. Disabling may improve performance."
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHAREININSTANCE_MENUTEXT"] = "Share in instance"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHAREININSTANCE_TEXT"] = "share while in instance"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHAREININSTANCE_TOOLTIP"] = "If enabled, you will repond to queries while you are in an instance. Disabling may improve performance."
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHAREITEMS_MENUTEXT"] = "Share items"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHAREITEMS_TEXT"] = "share your inventory items"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHAREITEMS_TOOLTIP"] = "If enabled, other Armory users who are using the same custom channel can search for items in your inventory."
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHAREQUESTS_MENUTEXT"] = "Share quests"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHAREQUESTS_TEXT"] = "share your quests"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHAREQUESTS_TOOLTIP"] = "If enabled, other Armory users can search your quests."
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHARESKILLS_MENUTEXT"] = "Share professions"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHARESKILLS_TEXT"] = "share your profession recipes"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHARESKILLS_TOOLTIP"] = "If enabled, other Armory users can search your recipes."
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOW2NDSKILLRANK_MENUTEXT"] = "Include secondary skills"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOW2NDSKILLRANK_TEXT"] = "include secondary skill ranks"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOW2NDSKILLRANK_TOOLTIP"] = "If enabled, skill ranks are added for secondary skills; otherwise only for primary skills."
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWACHIEVEMENTS_MENUTEXT"] = "Show achievements in links"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWACHIEVEMENTS_TEXT"] = "show characters in linked achievements"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWACHIEVEMENTS_TOOLTIP"] = "If enabled, characters that earned or are in progress with the achievement linked in the chat frame are added to its tooltip."
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWALTEQUIP_MENUTEXT"] = "Show alternative equipment"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWALTEQUIP_TEXT"] = "show alternative equipment slots"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWALTEQUIP_TOOLTIP"] = "If enabled, the paperdoll will show other inventory items that may fit the equipment slot."
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWCANLEARN_MENUTEXT"] = "Show 'learnable by' in tooltips"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWCANLEARN_TEXT"] = "show 'learnable by' in tooltips"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWCANLEARN_TOOLTIP"] = "If enabled, tooltips will show which character can learn the recipe or glyph."
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWCOUNTTOTAL_MENUTEXT"] = "Show item count totals"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWCOUNTTOTAL_TEXT"] = "include item count totals"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWCOUNTTOTAL_TOOLTIP"] = "If enabled a grand total will be added to the item counts."
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWCRAFTERS_MENUTEXT"] = "Show crafters in tooltips"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWCRAFTERS_TEXT"] = "show crafters in tooltips"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWCRAFTERS_TOOLTIP"] = "If enabled, item tooltips will show which character can craft that item."
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWEQCTOOLTIPS_MENUTEXT"] = "Show comparison tooltips"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWEQCTOOLTIPS_TEXT"] = "show equipment comparison tooltips"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWEQCTOOLTIPS_TOOLTIP"] = "If enabled, comparison tooltips will be shown when the Alt key is pressed while an equipment game tooltip is visible."
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWGEARSETS_MENUTEXT"] = "Show gear sets in tooltip"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWGEARSETS_TEXT"] = "show equipment set names in tooltips"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWGEARSETS_TOOLTIP"] = "If enabled and equipment belongs to a gear set, the name of the set will be shown in its tooltip."
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWGEMS_MENUTEXT"] = "Show gemming details"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWGEMS_TEXT"] = "show socket gemming details in tooltips"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWGEMS_TOOLTIP"] = "If enabled, the color of the socket and the name of the gem will be added to the item tooltip."
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWHASSKILL_MENUTEXT"] = "Show 'attainable by' in tooltips"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWHASSKILL_TEXT"] = "show 'attainable by' in tooltips"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWHASSKILL_TOOLTIP"] = "If enabled, tooltips will show which character will eventually be able to learn the recipe or glyph."
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWITEMCOUNT_MENUTEXT"] = "Show tooltip item counts"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWITEMCOUNT_TEXT"] = "show item counts in tooltips"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWITEMCOUNT_TOOLTIP"] = "If enabled, item tooltips will show owned totals per character."
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWKNOWNBY_MENUTEXT"] = "Show 'known by' in tooltips"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWKNOWNBY_TEXT"] = "show 'known by' in tooltips"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWKNOWNBY_TOOLTIP"] = "If enabled, tooltips will show which character already knows the recipe or glyph."
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWMINIMAP_MENUTEXT"] = "Show minimap button"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWMINIMAP_TEXT"] = "show minimap button"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWMINIMAP_TOOLTIP"] = "If enabled, an easy access button is attached to the minimap."
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWMMGLOBAL_MENUTEXT"] = "minimap button for all"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWMMGLOBAL_TEXT"] = "Use one minimap button for all characters"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWMMGLOBAL_TOOLTIP"] = "If enabled, one minimap button will be shown for all characters. If not, you'll have to enable or disable the minimap button for each character individually."
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWQUESTALTS_MENUTEXT"] = "Show alts in linked quests"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWQUESTALTS_TEXT"] = "show characters in linked quests"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWQUESTALTS_TOOLTIP"] = "If enabled, characters that are on the quest linked in the chat frame are added to its tooltip."
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWSHAREMSG_MENUTEXT"] = "Show share messages"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWSHAREMSG_TEXT"] = "show data sharing messages"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWSHAREMSG_TOOLTIP"] = "If enabled, messages will be written to the chat frame that provide information about data sharing events."
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWSKILLRANK_MENUTEXT"] = "Show skill ranks in tooltips"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWSKILLRANK_TEXT"] = "show skill ranks in tooltips"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWSKILLRANK_TOOLTIP"] = "If enabled, skill ranks are added to skill button tooltips."
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWSUMMARY_MENUTEXT"] = "Summary sheet"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWSUMMARY_TEXT"] = "show summary sheet"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWSUMMARY_TOOLTIP"] = "If enabled a character summary sheet will be show when hovering over the minimap or LDB button."
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWUNEQUIP_MENUTEXT"] = "Show unequippable alternatives"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWUNEQUIP_TEXT"] = "show unequippable alternatives"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SHOWUNEQUIP_TOOLTIP"] = "If enabled, all inventory items that will fit the slot will be shown regardless of prerequisites."
--[[Translation missing --]]
L["ARMORY_CMD_SET_SUCCESS"] = "%1$s set to %2$s"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SUMMARYDELAY_TEXT"] = "Popup Delay"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SUMMARYDELAY_TOOLTIP"] = "Adjust the delay at which the summary will be shown."
--[[Translation missing --]]
L["ARMORY_CMD_SET_SYSTEMWARNINGS_MENUTEXT"] = "Enable system warnings"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SYSTEMWARNINGS_TEXT"] = "enable system warning messages"
--[[Translation missing --]]
L["ARMORY_CMD_SET_SYSTEMWARNINGS_TOOLTIP"] = [=[If enabled, warning messages are displayed when something is wrong (e.g. the server is not returning any data).
 
You are strongly advised to keep this setting enabled. It is generally better to find the cause of the message and solve the issue. For example disabling the subclass and slot filters can be used as a workaround to prevent most trade skill update warnings. As a trade-off you'll lose some functionality though.]=]
--[[Translation missing --]]
L["ARMORY_CMD_SET_USECLASSCOLORS_MENUTEXT"] = "Use class colors"
--[[Translation missing --]]
L["ARMORY_CMD_SET_USECLASSCOLORS_TEXT"] = "use class colors for character names"
--[[Translation missing --]]
L["ARMORY_CMD_SET_USECLASSCOLORS_TOOLTIP"] = "If enabled, class colors are used when displaying character names."
--[[Translation missing --]]
L["ARMORY_CMD_SET_USEENCODING_MENUTEXT"] = "Prefer memory over CPU"
--[[Translation missing --]]
L["ARMORY_CMD_SET_USEENCODING_TEXT"] = "prefer memory usage over processing speed"
--[[Translation missing --]]
L["ARMORY_CMD_SET_USEENCODING_TOOLTIP"] = "If enabled, data will will stored in a binary encoded format taking up less memory but using more CPU for storage and retrieval. Enabling this option will decrease performance,"
--[[Translation missing --]]
L["ARMORY_CMD_SET_USEFACTIONFILTER_MENUTEXT"] = "Realm & faction filter"
--[[Translation missing --]]
L["ARMORY_CMD_SET_USEFACTIONFILTER_TEXT"] = "enable realm and faction filter"
--[[Translation missing --]]
L["ARMORY_CMD_SET_USEFACTIONFILTER_TOOLTIP"] = [=[If enabled, only characters on the current and connected realms and belonging to the current faction will be shown. This will also affect tooltip information.
Note that for item counts there is a separate realm and faction setting.]=]
--[[Translation missing --]]
L["ARMORY_CMD_SET_USEINPROGRESSCOLOR_MENUTEXT"] = "Use different color for 'in progress'"
--[[Translation missing --]]
L["ARMORY_CMD_SET_USEINPROGRESSCOLOR_TEXT"] = "colorize 'in progress' differently"
--[[Translation missing --]]
L["ARMORY_CMD_SET_USEINPROGRESSCOLOR_TOOLTIP"] = "If enabled, a different color will be used for achievements still in progress by a character."
--[[Translation missing --]]
L["ARMORY_CMD_SET_USEMAZIEL_MENUTEXT"] = "Use two stat panels"
--[[Translation missing --]]
L["ARMORY_CMD_SET_USEMAZIEL_TEXT"] = "hide talent build and professions"
--[[Translation missing --]]
L["ARMORY_CMD_SET_USEMAZIEL_TOOLTIP"] = "If enabled, the talent and profession frames will be replaced by a second stat panel."
--[[Translation missing --]]
L["ARMORY_CMD_SET_USEOVERLAY_MENUTEXT"] = "Enable character model overlay"
--[[Translation missing --]]
L["ARMORY_CMD_SET_USEOVERLAY_TEXT"] = "replace character model with Armory layout"
--[[Translation missing --]]
L["ARMORY_CMD_SET_USEOVERLAY_TOOLTIP"] = "If enabled, Armory's layout will replace the character model when the character frame is collapsed."
--[[Translation missing --]]
L["ARMORY_CMD_SET_WARNINGSOUND_MENUTEXT"] = "Warning sound"
--[[Translation missing --]]
L["ARMORY_CMD_SET_WARNINGSOUND_TEXT"] = "warning message sound"
--[[Translation missing --]]
L["ARMORY_CMD_SET_WARNINGSOUND_TOOLTIP"] = "Select a sound to play when an automated warning or error message is displayed in the chat frame."
--[[Translation missing --]]
L["ARMORY_CMD_SET_WEEKLYRESET_MENUTEXT"] = "Weekly reset"
--[[Translation missing --]]
L["ARMORY_CMD_SET_WEEKLYRESET_TEXT"] = "weekly server reset"
--[[Translation missing --]]
L["ARMORY_CMD_SET_WEEKLYRESET_TOOLTIP"] = "Select the day on which the server resets weekly (Tuesday for US servers and Wednesday for EU servers)."
--[[Translation missing --]]
L["ARMORY_CMD_SET_WINDOWSEARCH_MENUTEXT"] = "Show find results in window"
--[[Translation missing --]]
L["ARMORY_CMD_SET_WINDOWSEARCH_TEXT"] = "show find command results in a dedicated window"
--[[Translation missing --]]
L["ARMORY_CMD_SET_WINDOWSEARCH_TOOLTIP"] = "If enabled, the results of the find command will be presented in a separate window; otherwise the results are shown in the chat window."
--[[Translation missing --]]
L["ARMORY_CMD_TOGGLE"] = "toggle Armory on or off"
--[[Translation missing --]]
L["ARMORY_CMD_USAGE"] = "Usage:"
--[[Translation missing --]]
L["ARMORY_COOLDOWN_AVAILABLE"] = "Cooldown of '%1$s' is available again for %2$s (%3$s)."
--[[Translation missing --]]
L["ARMORY_COOLDOWN_WARNING"] = "%s in %d |4minute:minutes;"
--[[Translation missing --]]
L["ARMORY_CRAFTABLE_BY"] = "Craftable by"
--[[Translation missing --]]
L["ARMORY_DB_INCOMPATIBLE"] = [=[The database is not compatible with this version of Armory and will be cleared.
You need to enter the world with every character to rebuild the database.]=]
--[[Translation missing --]]
L["ARMORY_DELETE_UNIT"] = "Do you want to remove %s from the database?"
--[[Translation missing --]]
L["ARMORY_DELETE_UNIT_HINT"] = "Right-click to delete."
--[[Translation missing --]]
L["ARMORY_EQUIPMENT"] = "Equipment"
--[[Translation missing --]]
L["ARMORY_EQUIPPED"] = "Equipped"
--[[Translation missing --]]
L["ARMORY_ERROR"] = "ERROR"
--[[Translation missing --]]
L["ARMORY_EVENT_WARNING"] = "%s starts in %d |4minute:minutes;"
--[[Translation missing --]]
L["ARMORY_EXPIRATION_LABEL"] = "Expiration"
--[[Translation missing --]]
L["ARMORY_EXPIRATION_SUBTEXT"] = "These options allow you to change the behavior of the mail expiration check."
--[[Translation missing --]]
L["ARMORY_EXPIRATION_TITLE"] = "Mail Expiration"
--[[Translation missing --]]
L["ARMORY_EXTENDED"] = "Extended"
--[[Translation missing --]]
L["ARMORY_FILTER_ALL"] = "Select all"
--[[Translation missing --]]
L["ARMORY_FILTER_CLEAR"] = "Clear selection"
--[[Translation missing --]]
L["ARMORY_FILTER_DISABLE"] = "Disable filters"
--[[Translation missing --]]
L["ARMORY_FILTER_ENABLE"] = "Enable filters"
--[[Translation missing --]]
L["ARMORY_FILTER_LABEL"] = "Filters: %s"
--[[Translation missing --]]
L["ARMORY_FILTER_TOOLTIP"] = "Click to access the global item filters."
--[[Translation missing --]]
L["ARMORY_FIND_BUTTON"] = "Find"
--[[Translation missing --]]
L["ARMORY_FIND_LABEL"] = "Find"
--[[Translation missing --]]
L["ARMORY_FIND_SUBTEXT"] = "These options allow you to change the behavior of the find command."
--[[Translation missing --]]
L["ARMORY_FIND_TITLE"] = "Search Database"
--[[Translation missing --]]
L["ARMORY_FONT_COLOR"] = "Font color"
--[[Translation missing --]]
L["ARMORY_FULLY_RESTED"] = "Fully rested in: %s"
--[[Translation missing --]]
L["ARMORY_GLOBAL"] = "Global"
L["ARMORY_GLYPH"] = "雕紋"
--[[Translation missing --]]
L["ARMORY_IGNORE_REASON_COMBAT"] = "sharing disabled while in combat"
--[[Translation missing --]]
L["ARMORY_IGNORE_REASON_INSTANCE"] = "sharing disabled while in instance"
--[[Translation missing --]]
L["ARMORY_IGNORE_REASON_SHARING"] = "sharing disabled"
--[[Translation missing --]]
L["ARMORY_IGNORE_REASON_VERSION"] = "unsupported protocol version"
--[[Translation missing --]]
L["ARMORY_INFO"] = "INFO"
--[[Translation missing --]]
L["ARMORY_INVALID_ITEM"] = "Invalid item, please rescan."
--[[Translation missing --]]
L["ARMORY_INVENTORY_BAGLAYOUT"] = "Use bag layout"
--[[Translation missing --]]
L["ARMORY_INVENTORY_BAGLAYOUT_TOOLTIP"] = "Show containers in accordance with the actual layout."
--[[Translation missing --]]
L["ARMORY_INVENTORY_ICONVIEW"] = "Icon view"
--[[Translation missing --]]
L["ARMORY_INVENTORY_ICONVIEW_TOOLTIP"] = "Standard view"
--[[Translation missing --]]
L["ARMORY_INVENTORY_LISTVIEW"] = "List view"
--[[Translation missing --]]
L["ARMORY_INVENTORY_LISTVIEW_TOOLTIP"] = "Advanced view"
--[[Translation missing --]]
L["ARMORY_INVENTORY_SEARCH_ALL"] = "All characters"
--[[Translation missing --]]
L["ARMORY_INVENTORY_SEARCH_ALL_TOOLTIP"] = "Select all inventory items of all characters in the database."
--[[Translation missing --]]
L["ARMORY_INVENTORY_SEARCH_TEXT_TOOLTIP"] = [=[Enter your filter criterion.

Note that you can filter on quality by entering '=' followed by %s, %s, %s, %s, %s, %s, %s or %s or their respective numeric identifier 0-7 (e.g. '=4' for epic items).]=]
--[[Translation missing --]]
L["ARMORY_KNOWN_BY"] = "Known by"
--[[Translation missing --]]
L["ARMORY_LINK_HINT"] = "Shift-click to link"
--[[Translation missing --]]
L["ARMORY_LINK_TRADESKILL_TOOLTIP"] = "Shift-click opens your profession."
--[[Translation missing --]]
L["ARMORY_LOOKUP_BUTTON"] = "Lookup"
--[[Translation missing --]]
L["ARMORY_LOOKUP_CHARACTER"] = "Lookup character"
--[[Translation missing --]]
L["ARMORY_LOOKUP_CHARACTER_SEARCH_TOOLTIP"] = [=[Enter your filter criterion.

Note that this can also be the name of someone's alt.]=]
--[[Translation missing --]]
L["ARMORY_LOOKUP_DETAIL"] = "Click for details"
--[[Translation missing --]]
L["ARMORY_LOOKUP_DISABLED"] = "Data sharing is disabled."
--[[Translation missing --]]
L["ARMORY_LOOKUP_IGNORED"] = "Request ignored (reason: %s)"
--[[Translation missing --]]
L["ARMORY_LOOKUP_ITEM"] = "Lookup item"
--[[Translation missing --]]
L["ARMORY_LOOKUP_NODETAIL"] = "No details available"
--[[Translation missing --]]
L["ARMORY_LOOKUP_NOT_CACHED"] = "Item information missing; please retry"
--[[Translation missing --]]
L["ARMORY_LOOKUP_PLAYER_HINT"] = [=[Shift-click for player info
Right-click to whisper]=]
--[[Translation missing --]]
L["ARMORY_LOOKUP_QUEST"] = "Lookup quests"
--[[Translation missing --]]
L["ARMORY_LOOKUP_QUEST_AREA"] = "Quest area"
--[[Translation missing --]]
L["ARMORY_LOOKUP_QUEST_NAME"] = "Quest name"
--[[Translation missing --]]
L["ARMORY_LOOKUP_QUEST_SEARCH_TOOLTIP"] = [=[Enter your filter criterion.

Note that you also request for characters having quests in a certain area by selecting the corresponding option in the dropdown.]=]
--[[Translation missing --]]
L["ARMORY_LOOKUP_REALM_ALIAS"] = "Looked up"
--[[Translation missing --]]
L["ARMORY_LOOKUP_REQUEST_DETAIL"] = "Requested data: %s"
--[[Translation missing --]]
L["ARMORY_LOOKUP_REQUEST_RECEIVED"] = "Data sharing request received from %s"
--[[Translation missing --]]
L["ARMORY_LOOKUP_REQUEST_SENT"] = "Request sent to %s"
--[[Translation missing --]]
L["ARMORY_LOOKUP_RESPONSE_RECEIVED"] = "Data received from %s"
--[[Translation missing --]]
L["ARMORY_LOOKUP_RESPONSE_SENT"] = "Response sent to %s"
--[[Translation missing --]]
L["ARMORY_LOOKUP_SEARCH_EXACT"] = "Exact match"
--[[Translation missing --]]
L["ARMORY_LOOKUP_SKILL"] = "Lookup recipes"
--[[Translation missing --]]
L["ARMORY_LOOKUP_SKILL_SEARCH_TOOLTIP"] = [=[Enter your filter criterion.

Character names returned can be clicked to access their skill window.
Note that you can request a full recipe list by entering just an asterisk (*).]=]
--[[Translation missing --]]
L["ARMORY_MAIL_COUNT_WARNING1"] = "The inbox still contains %d |4mail:mails; that couldn't be scanned."
--[[Translation missing --]]
L["ARMORY_MAIL_COUNT_WARNING2"] = "%1$s (%2$s) has %d |4mail:mails; that couldn't be scanned."
--[[Translation missing --]]
L["ARMORY_MAIL_COUNT_WARNING3"] = "Unknown sender detected. Please reopen your mail to force a rescan if this is unexpected."
--[[Translation missing --]]
L["ARMORY_MAIL_ITEM_COUNT"] = "Number of items:"
--[[Translation missing --]]
L["ARMORY_MAIL_LAST_VISIT"] = "Last visit:"
--[[Translation missing --]]
L["ARMORY_MAIL_REMAINING"] = "Mail remaining:"
--[[Translation missing --]]
L["ARMORY_MAIL_VISIT_WARNING"] = "%1$s (%2$s) hasn't visited the mailbox for %3$s. Please log in to check your inbox."
--[[Translation missing --]]
L["ARMORY_MINIMAP_LABEL"] = "Minimap"
--[[Translation missing --]]
L["ARMORY_MINIMAP_SUBTEXT"] = "These options control the display of the minimap button."
--[[Translation missing --]]
L["ARMORY_MINIMAP_TITLE"] = "Armory Minimap Button"
--[[Translation missing --]]
L["ARMORY_MISC_LABEL"] = "Miscellaneous"
--[[Translation missing --]]
L["ARMORY_MISC_SUBTEXT"] = "These options allow you to change various settings."
--[[Translation missing --]]
L["ARMORY_MISC_TITLE"] = "Miscellaneous Options"
--[[Translation missing --]]
L["ARMORY_MODULES_LABEL"] = "Modules"
--[[Translation missing --]]
L["ARMORY_MODULES_SUBTEXT"] = "These options allow you to select which modules should be active."
--[[Translation missing --]]
L["ARMORY_MODULES_TITLE"] = "Armory Modules"
--[[Translation missing --]]
L["ARMORY_MONEY_TOTAL"] = "%1$s %2$s total:"
--[[Translation missing --]]
L["ARMORY_NO_DATA"] = "No data available"
--[[Translation missing --]]
L["ARMORY_OPEN_HINT"] = "Click to open"
--[[Translation missing --]]
L["ARMORY_PANDARIA_GEM_RESEARCH"] = "Pandaria Gem Research"
--[[Translation missing --]]
L["ARMORY_QUEST_TOOLTIP_LABEL"] = "Alts on this quest:"
L["ARMORY_RECIPE"] = "配方"
--[[Translation missing --]]
L["ARMORY_RECIPE_WARNING"] = [=[Recipe %s not found in LibRecipes. Trying to make an educated guess.
Please check with '/armory find skill ...' to be sure.]=]
--[[Translation missing --]]
L["ARMORY_REPUTATION_SUMMARY"] = "%1$s - %2$s (%3$d/%4$d, %5$d left)"
--[[Translation missing --]]
L["ARMORY_SEARCHING"] = "Searching..."
--[[Translation missing --]]
L["ARMORY_SELECT_UNIT_HINT"] = "Left-click to select this character."
--[[Translation missing --]]
L["ARMORY_SHARE_DOWNLOAD_LOADERROR"] = "Could not load %1$s; reason: %2$s"
--[[Translation missing --]]
L["ARMORY_SHARE_LABEL"] = "Sharing"
--[[Translation missing --]]
L["ARMORY_SHARE_SUBTEXT1"] = "These options define how you share your data with other Armory users. Note that these settings are on a per-character basis."
--[[Translation missing --]]
L["ARMORY_SHARE_SUBTEXT2"] = "The following options are set at a global level."
--[[Translation missing --]]
L["ARMORY_SHARE_TITLE"] = "Data Sharing"
L["ARMORY_SHORTDATE_FORMAT"] = "ARMORY_SHORTDATE_FORMAT"
L["ARMORY_SLASH_ALTERNATIVES"] = "/ar"
--[[Translation missing --]]
L["ARMORY_SOCIAL_ADD_TOOLTIP"] = "Shift-click to add to your current list."
--[[Translation missing --]]
L["ARMORY_SUBTEXT"] = "These options allow you to modify Armory's behavior."
--[[Translation missing --]]
L["ARMORY_SUMMARY_LABEL"] = "Summary"
--[[Translation missing --]]
L["ARMORY_SUMMARY_SUBTEXT1"] = "These options allow you to change Armory's character summary sheet."
--[[Translation missing --]]
L["ARMORY_SUMMARY_SUBTEXT2"] = "Select the information to show."
--[[Translation missing --]]
L["ARMORY_SUMMARY_TITLE"] = "Summary Options"
--[[Translation missing --]]
L["ARMORY_TALENTS"] = "TALENT SPECIALIZATION:"
--[[Translation missing --]]
L["ARMORY_TOOLTIP_HINT1"] = "Left-click toggles Armory"
--[[Translation missing --]]
L["ARMORY_TOOLTIP_HINT2"] = "Right-click for options"
--[[Translation missing --]]
L["ARMORY_TOOLTIP_LABEL"] = "Tooltip"
--[[Translation missing --]]
L["ARMORY_TOOLTIP_SUBTEXT"] = "These options allow you to add information to tooltips."
--[[Translation missing --]]
L["ARMORY_TOOLTIP_TITLE"] = "Tooltip Enhancement"
--[[Translation missing --]]
L["ARMORY_TOOLTIP1"] = "Character:"
--[[Translation missing --]]
L["ARMORY_TOOLTIP2"] = "Realm:"
--[[Translation missing --]]
L["ARMORY_TOTAL"] = "Total: %d"
L["ARMORY_TRADE_ALCHEMY"] = "鍊金術"
L["ARMORY_TRADE_BLACKSMITHING"] = "鍛造"
L["ARMORY_TRADE_COOKING"] = "烹飪"
L["ARMORY_TRADE_ENCHANTING"] = "附魔"
L["ARMORY_TRADE_ENGINEERING"] = "工程學"
L["ARMORY_TRADE_FIRST_AID"] = "急救"
L["ARMORY_TRADE_FISHING"] = "釣魚"
L["ARMORY_TRADE_HERBALISM"] = "草藥學"
L["ARMORY_TRADE_INSCRIPTION"] = "銘文學"
L["ARMORY_TRADE_JEWELCRAFTING"] = "珠寶設計"
L["ARMORY_TRADE_LEATHERWORKING"] = "製皮"
L["ARMORY_TRADE_MINING"] = "採礦"
--[[Translation missing --]]
L["ARMORY_TRADE_POISONS"] = "Poisons"
--[[Translation missing --]]
L["ARMORY_TRADE_SKILLS"] = "PRIMARY PROFESSIONS:"
L["ARMORY_TRADE_SKINNING"] = "剝皮"
L["ARMORY_TRADE_TAILORING"] = "裁縫"
--[[Translation missing --]]
L["ARMORY_TRADE_UPDATE_FAILED"] = "Profession data incomplete. Please reopen and close your profession window again."
--[[Translation missing --]]
L["ARMORY_TRADE_UPDATE_WARNING"] = "Profession data not saved. Please use the close button to trigger an update."
--[[Translation missing --]]
L["ARMORY_TRADESKILL_SEARCH_TEXT_TOOLTIP"] = [=[Enter your filter criterion.

Note that you can also enter for example '10', '~10' or '10-20' to filter on recipe level.]=]
L["ARMORY_TRANSMUTE"] = "轉化"
--[[Translation missing --]]
L["ARMORY_UPDATE_SUSPENDED"] = "suspended"
--[[Translation missing --]]
L["ARMORY_VOID_STORAGE_ABBR"] = "Void"
L["ARMORY_WARNING"] = "警告"
--[[Translation missing --]]
L["ARMORY_WHAT"] = "What"
--[[Translation missing --]]
L["ARMORY_WHERE"] = "Where"
--[[Translation missing --]]
L["ARMORY_WHO"] = "Who"
--[[Translation missing --]]
L["ARMORY_WILL_LEARN"] = "Attainable by"
--[[Translation missing --]]
L["ARMORY_XP_SUMMARY"] = "Level %1$d (%2$s) %3$d XP to go, %4$s rested"
--[[Translation missing --]]
L["BINDING_NAME_ARMORY_ACHIEVEMENT"] = "Open achievement pane"
--[[Translation missing --]]
L["BINDING_NAME_ARMORY_CHARACTER"] = "Open character frame"
--[[Translation missing --]]
L["BINDING_NAME_ARMORY_CURRENCY"] = "Open currency frame"
--[[Translation missing --]]
L["BINDING_NAME_ARMORY_INVENTORY"] = "Open inventory"
--[[Translation missing --]]
L["BINDING_NAME_ARMORY_PET"] = "Open pet frame"
--[[Translation missing --]]
L["BINDING_NAME_ARMORY_PVP"] = "Open PVP frame"
--[[Translation missing --]]
L["BINDING_NAME_ARMORY_QUEST"] = "Open quest log"
--[[Translation missing --]]
L["BINDING_NAME_ARMORY_RAID"] = "Open raid frame"
--[[Translation missing --]]
L["BINDING_NAME_ARMORY_REPUTATION"] = "Open reputation frame"
--[[Translation missing --]]
L["BINDING_NAME_ARMORY_SOCIAL"] = "Open social pane"
--[[Translation missing --]]
L["BINDING_NAME_ARMORY_SPELLBOOK"] = "Open spellbook"
--[[Translation missing --]]
L["BINDING_NAME_ARMORY_TALENT"] = "Open talent frame"
--[[Translation missing --]]
L["BINDING_NAME_ARMORY_TOGGLE"] = "Toggle Armory"
--[[Translation missing --]]
L["BINDING_NAME_ARMORY_TRADESKILL1"] = "Open primary profession 1"
--[[Translation missing --]]
L["BINDING_NAME_ARMORY_TRADESKILL2"] = "Open primary profession 2"
--[[Translation missing --]]
L["BINDING_NAME_CURRENT_CHARACTER"] = "Select current character"
--[[Translation missing --]]
L["BINDING_NAME_FIND"] = "Toggle database search"
--[[Translation missing --]]
L["BINDING_NAME_LOOKUP"] = "Toggle lookup"
--[[Translation missing --]]
L["BINDING_NAME_NEXT_CHARACTER"] = "Select next character"
--[[Translation missing --]]
L["BINDING_NAME_PREVIOUS_CHARACTER"] = "Select previous character"

