--[[

    Please do NOT edit this file but go to http://wow.curseforge.com/addons/armory/localization/ instead.

    Original translators: 한글화 TalksWind (PaperTiger), 덫붙임 Hellguard
    
    The contents of this file will be generated automatically.
    
]]--

local L = LibStub("AceLocale-3.0"):NewLocale("ArmoryGuildBank", "koKR");
if ( not L ) then 
    return;
end

--@localization(locale="koKR", format="lua_additive_table", handle-unlocalized="english", namespace="GuildBank", handle-subnamespaces="none")@
